# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/abci_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ABCI_Plot(object):
    def setupUi(self, ABCI_Plot):
        ABCI_Plot.setObjectName("ABCI_Plot")
        ABCI_Plot.resize(341, 340)
        self.gridLayout = QtWidgets.QGridLayout(ABCI_Plot)
        self.gridLayout.setObjectName("gridLayout")
        self.w_Bottom = QtWidgets.QWidget(ABCI_Plot)
        self.w_Bottom.setMinimumSize(QtCore.QSize(250, 250))
        self.w_Bottom.setMaximumSize(QtCore.QSize(250, 250))
        self.w_Bottom.setStyleSheet("background-color:transparent;")
        self.w_Bottom.setObjectName("w_Bottom")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.w_Bottom)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.w_Bottom)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_2.addWidget(self.comboBox, 4, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.w_Bottom)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.w_Bottom)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 4, 2, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.w_Bottom)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 3, 1, 1, 1)
        self.checkableComboBox = QCheckableComboBox(self.w_Bottom)
        self.checkableComboBox.setObjectName("checkableComboBox")
        self.gridLayout_2.addWidget(self.checkableComboBox, 2, 0, 1, 3)
        self.comboBox_3 = QtWidgets.QComboBox(self.w_Bottom)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.w_Bottom)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_2.addWidget(self.comboBox_2, 0, 0, 1, 1)
        self.checkableComboBox_2 = QCheckableComboBox(self.w_Bottom)
        self.checkableComboBox_2.setObjectName("checkableComboBox_2")
        self.gridLayout_2.addWidget(self.checkableComboBox_2, 1, 0, 1, 3)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.w_Bottom)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_2.addWidget(self.doubleSpinBox, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.w_Bottom, 0, 0, 1, 1)

        self.retranslateUi(ABCI_Plot)
        QtCore.QMetaObject.connectSlotsByName(ABCI_Plot)

    def retranslateUi(self, ABCI_Plot):
        _translate = QtCore.QCoreApplication.translate
        ABCI_Plot.setWindowTitle(_translate("ABCI_Plot", "Form"))
from QCheckableComboBox import QCheckableComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ABCI_Plot = QtWidgets.QWidget()
    ui = Ui_ABCI_Plot()
    ui.setupUi(ABCI_Plot)
    ABCI_Plot.show()
    sys.exit(app.exec_())
