# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/edit_annotated_text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EAT(object):
    def setupUi(self, EAT):
        EAT.setObjectName("EAT")
        EAT.resize(321, 75)
        EAT.setMinimumSize(QtCore.QSize(0, 75))
        EAT.setMaximumSize(QtCore.QSize(16777215, 75))
        self.gridLayout = QtWidgets.QGridLayout(EAT)
        self.gridLayout.setContentsMargins(0, 0, 0, 11)
        self.gridLayout.setObjectName("gridLayout")
        self.pb_Apply = QtWidgets.QPushButton(EAT)
        self.pb_Apply.setObjectName("pb_Apply")
        self.gridLayout.addWidget(self.pb_Apply, 1, 0, 1, 1)
        self.pb_Cancel = QtWidgets.QPushButton(EAT)
        self.pb_Cancel.setObjectName("pb_Cancel")
        self.gridLayout.addWidget(self.pb_Cancel, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(EAT)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb_Box = QtWidgets.QComboBox(self.widget)
        self.cb_Box.setObjectName("cb_Box")
        self.cb_Box.addItem("")
        self.cb_Box.addItem("")
        self.cb_Box.addItem("")
        self.cb_Box.addItem("")
        self.gridLayout_2.addWidget(self.cb_Box, 0, 2, 1, 1)
        self.le_Text = QtWidgets.QLineEdit(self.widget)
        self.le_Text.setObjectName("le_Text")
        self.gridLayout_2.addWidget(self.le_Text, 0, 0, 1, 2)
        self.sb_Font_Size = QtWidgets.QSpinBox(self.widget)
        self.sb_Font_Size.setMinimum(5)
        self.sb_Font_Size.setProperty("value", 14)
        self.sb_Font_Size.setObjectName("sb_Font_Size")
        self.gridLayout_2.addWidget(self.sb_Font_Size, 0, 3, 1, 1)
        self.sb_Rotation = QtWidgets.QSpinBox(self.widget)
        self.sb_Rotation.setMaximum(360)
        self.sb_Rotation.setObjectName("sb_Rotation")
        self.gridLayout_2.addWidget(self.sb_Rotation, 0, 4, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(EAT)
        QtCore.QMetaObject.connectSlotsByName(EAT)

    def retranslateUi(self, EAT):
        _translate = QtCore.QCoreApplication.translate
        EAT.setWindowTitle(_translate("EAT", "Form"))
        self.pb_Apply.setText(_translate("EAT", "Apply"))
        self.pb_Cancel.setText(_translate("EAT", "Cancel"))
        self.cb_Box.setItemText(0, _translate("EAT", "None"))
        self.cb_Box.setItemText(1, _translate("EAT", "Round"))
        self.cb_Box.setItemText(2, _translate("EAT", "Square"))
        self.cb_Box.setItemText(3, _translate("EAT", "Round4"))
        self.le_Text.setText(_translate("EAT", "Text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EAT = QtWidgets.QWidget()
    ui = Ui_EAT()
    ui.setupUi(EAT)
    EAT.show()
    sys.exit(app.exec_())
