# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/geometry_input.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Geometry_Input(object):
    def setupUi(self, Geometry_Input):
        Geometry_Input.setObjectName("Geometry_Input")
        Geometry_Input.resize(376, 698)
        self.gridLayout = QtWidgets.QGridLayout(Geometry_Input)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Geometry_Input)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -591, 376, 1235))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.w_Load_Manual = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Load_Manual.setStyleSheet("    border-radius: 15px;")
        self.w_Load_Manual.setObjectName("w_Load_Manual")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.w_Load_Manual)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.cb_Shape_Entry_Mode = QtWidgets.QComboBox(self.w_Load_Manual)
        self.cb_Shape_Entry_Mode.setMinimumSize(QtCore.QSize(50, 50))
        self.cb_Shape_Entry_Mode.setMaximumSize(QtCore.QSize(150, 100))
        self.cb_Shape_Entry_Mode.setObjectName("cb_Shape_Entry_Mode")
        self.cb_Shape_Entry_Mode.addItem("")
        self.cb_Shape_Entry_Mode.addItem("")
        self.gridLayout_33.addWidget(self.cb_Shape_Entry_Mode, 0, 0, 1, 1)
        self.cb_Shape_Space_Keys = QCheckableComboBox(self.w_Load_Manual)
        self.cb_Shape_Space_Keys.setMinimumSize(QtCore.QSize(100, 0))
        self.cb_Shape_Space_Keys.setObjectName("cb_Shape_Space_Keys")
        self.gridLayout_33.addWidget(self.cb_Shape_Space_Keys, 1, 0, 1, 2)
        self.w_Select_Shape_Space = QtWidgets.QWidget(self.w_Load_Manual)
        self.w_Select_Shape_Space.setObjectName("w_Select_Shape_Space")
        self.gridLayout_86 = QtWidgets.QGridLayout(self.w_Select_Shape_Space)
        self.gridLayout_86.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_86.setObjectName("gridLayout_86")
        self.pb_Select_Shape_Space = QtWidgets.QPushButton(self.w_Select_Shape_Space)
        self.pb_Select_Shape_Space.setMinimumSize(QtCore.QSize(30, 0))
        self.pb_Select_Shape_Space.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_Select_Shape_Space.setObjectName("pb_Select_Shape_Space")
        self.gridLayout_86.addWidget(self.pb_Select_Shape_Space, 0, 3, 1, 1)
        self.le_Shape_Space = QtWidgets.QLineEdit(self.w_Select_Shape_Space)
        self.le_Shape_Space.setMinimumSize(QtCore.QSize(150, 0))
        self.le_Shape_Space.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_Shape_Space.setPlaceholderText("")
        self.le_Shape_Space.setObjectName("le_Shape_Space")
        self.gridLayout_86.addWidget(self.le_Shape_Space, 0, 1, 1, 1)
        self.gridLayout_33.addWidget(self.w_Select_Shape_Space, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.w_Load_Manual, 0, 0, 1, 1)
        self.widget_16 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_16.setStyleSheet("")
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_24.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.w_Expansion = QtWidgets.QWidget(self.widget_16)
        self.w_Expansion.setMinimumSize(QtCore.QSize(350, 0))
        self.w_Expansion.setMaximumSize(QtCore.QSize(350, 16777215))
        self.w_Expansion.setStyleSheet("#w_Expansion{\n"
"    border-radius: 15px;\n"
"}")
        self.w_Expansion.setObjectName("w_Expansion")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.w_Expansion)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.label_33 = QtWidgets.QLabel(self.w_Expansion)
        self.label_33.setMinimumSize(QtCore.QSize(25, 0))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_30.addWidget(self.label_33, 3, 0, 1, 1)
        self.le_c = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_c.setMinimumSize(QtCore.QSize(75, 0))
        self.le_c.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_c.setObjectName("le_c")
        self.gridLayout_30.addWidget(self.le_c, 3, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.w_Expansion)
        self.label_28.setMinimumSize(QtCore.QSize(25, 0))
        self.label_28.setObjectName("label_28")
        self.gridLayout_30.addWidget(self.label_28, 1, 6, 1, 1)
        self.le_Rbp_Lbp = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_Rbp_Lbp.setMinimumSize(QtCore.QSize(75, 0))
        self.le_Rbp_Lbp.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_Rbp_Lbp.setObjectName("le_Rbp_Lbp")
        self.gridLayout_30.addWidget(self.le_Rbp_Lbp, 1, 7, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.w_Expansion)
        self.label_27.setMinimumSize(QtCore.QSize(25, 0))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_30.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.w_Expansion)
        self.label_32.setMinimumSize(QtCore.QSize(25, 0))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_30.addWidget(self.label_32, 2, 0, 1, 1)
        self.le_b_t = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_b_t.setMinimumSize(QtCore.QSize(75, 0))
        self.le_b_t.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_b_t.setObjectName("le_b_t")
        self.gridLayout_30.addWidget(self.le_b_t, 2, 1, 1, 1)
        self.le_a_t = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_a_t.setMinimumSize(QtCore.QSize(75, 0))
        self.le_a_t.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_a_t.setObjectName("le_a_t")
        self.gridLayout_30.addWidget(self.le_a_t, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem, 5, 1, 1, 1)
        self.cb_Expansion = SwitchControl(self.w_Expansion)
        self.cb_Expansion.setObjectName("cb_Expansion")
        self.gridLayout_30.addWidget(self.cb_Expansion, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.w_Expansion, 7, 0, 1, 1)
        self.w_Outer_Cell_R = QtWidgets.QWidget(self.widget_16)
        self.w_Outer_Cell_R.setMinimumSize(QtCore.QSize(350, 200))
        self.w_Outer_Cell_R.setMaximumSize(QtCore.QSize(350, 16777215))
        self.w_Outer_Cell_R.setStyleSheet("#w_Outer_Cell_R{\n"
"    border-radius: 15px;\n"
"}")
        self.w_Outer_Cell_R.setObjectName("w_Outer_Cell_R")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.w_Outer_Cell_R)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.le_Req_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_Req_or.setReadOnly(True)
        self.le_Req_or.setObjectName("le_Req_or")
        self.gridLayout_31.addWidget(self.le_Req_or, 5, 1, 1, 1)
        self.l_Tune_Alternate_Variable_End_Cell_2 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.l_Tune_Alternate_Variable_End_Cell_2.setMinimumSize(QtCore.QSize(25, 0))
        self.l_Tune_Alternate_Variable_End_Cell_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.l_Tune_Alternate_Variable_End_Cell_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_Tune_Alternate_Variable_End_Cell_2.setObjectName("l_Tune_Alternate_Variable_End_Cell_2")
        self.gridLayout_31.addWidget(self.l_Tune_Alternate_Variable_End_Cell_2, 4, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_55.setObjectName("label_55")
        self.gridLayout_31.addWidget(self.label_55, 5, 0, 1, 1)
        self.le_B_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_B_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_B_or.setObjectName("le_B_or")
        self.gridLayout_31.addWidget(self.le_B_or, 1, 3, 1, 1)
        self.le_Ri_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_Ri_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Ri_or.setObjectName("le_Ri_or")
        self.gridLayout_31.addWidget(self.le_Ri_or, 4, 1, 1, 1)
        self.le_Alpha_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_Alpha_or.setObjectName("le_Alpha_or")
        self.gridLayout_31.addWidget(self.le_Alpha_or, 5, 3, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_40.setMinimumSize(QtCore.QSize(25, 0))
        self.label_40.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_31.addWidget(self.label_40, 3, 0, 1, 1)
        self.le_A_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_A_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_A_or.setObjectName("le_A_or")
        self.gridLayout_31.addWidget(self.le_A_or, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_38.setMinimumSize(QtCore.QSize(25, 0))
        self.label_38.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_31.addWidget(self.label_38, 4, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_53.setObjectName("label_53")
        self.gridLayout_31.addWidget(self.label_53, 5, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_48.setMinimumSize(QtCore.QSize(25, 0))
        self.label_48.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_31.addWidget(self.label_48, 1, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_45.setMinimumSize(QtCore.QSize(25, 0))
        self.label_45.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_31.addWidget(self.label_45, 1, 0, 1, 1)
        self.le_L_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_L_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_L_or.setObjectName("le_L_or")
        self.gridLayout_31.addWidget(self.le_L_or, 4, 3, 1, 1)
        self.le_a_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_a_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_a_or.setObjectName("le_a_or")
        self.gridLayout_31.addWidget(self.le_a_or, 3, 1, 1, 1)
        self.le_b_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_b_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_b_or.setObjectName("le_b_or")
        self.gridLayout_31.addWidget(self.le_b_or, 3, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_39.setMinimumSize(QtCore.QSize(25, 0))
        self.label_39.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_31.addWidget(self.label_39, 3, 2, 1, 1)
        self.cb_Outer_Cell_R = SwitchControl(self.w_Outer_Cell_R)
        self.cb_Outer_Cell_R.setObjectName("cb_Outer_Cell_R")
        self.gridLayout_31.addWidget(self.cb_Outer_Cell_R, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.w_Outer_Cell_R, 5, 0, 1, 1)
        self.w_Outer_Cell_L = QtWidgets.QWidget(self.widget_16)
        self.w_Outer_Cell_L.setMinimumSize(QtCore.QSize(350, 200))
        self.w_Outer_Cell_L.setMaximumSize(QtCore.QSize(350, 16777215))
        self.w_Outer_Cell_L.setStyleSheet("#w_Outer_Cell_L{\n"
"    border-radius: 15px;\n"
"}")
        self.w_Outer_Cell_L.setObjectName("w_Outer_Cell_L")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.w_Outer_Cell_L)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.le_Req_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_Req_ol.setReadOnly(True)
        self.le_Req_ol.setObjectName("le_Req_ol")
        self.gridLayout_28.addWidget(self.le_Req_ol, 5, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_51.setObjectName("label_51")
        self.gridLayout_28.addWidget(self.label_51, 5, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_14.setMinimumSize(QtCore.QSize(25, 0))
        self.label_14.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_28.addWidget(self.label_14, 3, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_20.setMinimumSize(QtCore.QSize(25, 0))
        self.label_20.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_28.addWidget(self.label_20, 3, 0, 1, 1)
        self.le_a_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_a_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_a_ol.setObjectName("le_a_ol")
        self.gridLayout_28.addWidget(self.le_a_ol, 3, 1, 1, 1)
        self.le_B_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_B_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_B_ol.setObjectName("le_B_ol")
        self.gridLayout_28.addWidget(self.le_B_ol, 1, 3, 1, 1)
        self.le_Alpha_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_Alpha_ol.setObjectName("le_Alpha_ol")
        self.gridLayout_28.addWidget(self.le_Alpha_ol, 5, 3, 1, 1)
        self.le_Ri_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_Ri_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Ri_ol.setObjectName("le_Ri_ol")
        self.gridLayout_28.addWidget(self.le_Ri_ol, 4, 1, 1, 1)
        self.le_b_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_b_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_b_ol.setObjectName("le_b_ol")
        self.gridLayout_28.addWidget(self.le_b_ol, 3, 3, 1, 1)
        self.l_Tune_Alternate_Variable_End_Cell = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.l_Tune_Alternate_Variable_End_Cell.setMinimumSize(QtCore.QSize(25, 0))
        self.l_Tune_Alternate_Variable_End_Cell.setMaximumSize(QtCore.QSize(25, 16777215))
        self.l_Tune_Alternate_Variable_End_Cell.setAlignment(QtCore.Qt.AlignCenter)
        self.l_Tune_Alternate_Variable_End_Cell.setObjectName("l_Tune_Alternate_Variable_End_Cell")
        self.gridLayout_28.addWidget(self.l_Tune_Alternate_Variable_End_Cell, 4, 2, 1, 1)
        self.le_L_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_L_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_L_ol.setObjectName("le_L_ol")
        self.gridLayout_28.addWidget(self.le_L_ol, 4, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_26.setMinimumSize(QtCore.QSize(25, 0))
        self.label_26.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_28.addWidget(self.label_26, 1, 2, 1, 1)
        self.le_A_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_A_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_A_ol.setObjectName("le_A_ol")
        self.gridLayout_28.addWidget(self.le_A_ol, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_5.setMinimumSize(QtCore.QSize(25, 0))
        self.label_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_28.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_52.setObjectName("label_52")
        self.gridLayout_28.addWidget(self.label_52, 5, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_25.setMinimumSize(QtCore.QSize(25, 0))
        self.label_25.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_28.addWidget(self.label_25, 1, 0, 1, 1)
        self.cb_Outer_Cell_L = SwitchControl(self.w_Outer_Cell_L)
        self.cb_Outer_Cell_L.setObjectName("cb_Outer_Cell_L")
        self.gridLayout_28.addWidget(self.cb_Outer_Cell_L, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.w_Outer_Cell_L, 3, 0, 1, 1)
        self.w_Inner_Cell = QtWidgets.QWidget(self.widget_16)
        self.w_Inner_Cell.setMinimumSize(QtCore.QSize(350, 200))
        self.w_Inner_Cell.setMaximumSize(QtCore.QSize(350, 16777215))
        self.w_Inner_Cell.setStyleSheet("#w_Inner_Cell{\n"
"    border-radius: 15px;\n"
"}")
        self.w_Inner_Cell.setObjectName("w_Inner_Cell")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.w_Inner_Cell)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.l_Tune_Alternate_Variable = QtWidgets.QLabel(self.w_Inner_Cell)
        self.l_Tune_Alternate_Variable.setMinimumSize(QtCore.QSize(25, 0))
        self.l_Tune_Alternate_Variable.setMaximumSize(QtCore.QSize(30, 16777215))
        self.l_Tune_Alternate_Variable.setAlignment(QtCore.Qt.AlignCenter)
        self.l_Tune_Alternate_Variable.setObjectName("l_Tune_Alternate_Variable")
        self.gridLayout_25.addWidget(self.l_Tune_Alternate_Variable, 4, 3, 1, 1)
        self.le_B_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_B_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_B_i.setObjectName("le_B_i")
        self.gridLayout_25.addWidget(self.le_B_i, 1, 4, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_49.setObjectName("label_49")
        self.gridLayout_25.addWidget(self.label_49, 5, 3, 1, 1)
        self.le_b_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_b_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_b_i.setObjectName("le_b_i")
        self.gridLayout_25.addWidget(self.le_b_i, 3, 4, 1, 1)
        self.le_A_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_A_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_A_i.setObjectName("le_A_i")
        self.gridLayout_25.addWidget(self.le_A_i, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_6.setMinimumSize(QtCore.QSize(27, 0))
        self.label_6.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_25.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_8.setMinimumSize(QtCore.QSize(27, 0))
        self.label_8.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_25.addWidget(self.label_8, 3, 1, 1, 1)
        self.le_a_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_a_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_a_i.setObjectName("le_a_i")
        self.gridLayout_25.addWidget(self.le_a_i, 3, 2, 1, 1)
        self.le_Alpha = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_Alpha.setObjectName("le_Alpha")
        self.gridLayout_25.addWidget(self.le_Alpha, 5, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_12.setMinimumSize(QtCore.QSize(27, 0))
        self.label_12.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_25.addWidget(self.label_12, 4, 1, 1, 1)
        self.le_L_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_L_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_L_i.setObjectName("le_L_i")
        self.gridLayout_25.addWidget(self.le_L_i, 4, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_7.setMinimumSize(QtCore.QSize(25, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_25.addWidget(self.label_7, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_11.setMinimumSize(QtCore.QSize(25, 0))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_25.addWidget(self.label_11, 3, 3, 1, 1)
        self.le_Ri_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_Ri_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Ri_i.setObjectName("le_Ri_i")
        self.gridLayout_25.addWidget(self.le_Ri_i, 4, 2, 1, 1)
        self.w_End_Cell_Tune_Extra_Variable = QtWidgets.QWidget(self.w_Inner_Cell)
        self.w_End_Cell_Tune_Extra_Variable.setObjectName("w_End_Cell_Tune_Extra_Variable")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.w_End_Cell_Tune_Extra_Variable)
        self.gridLayout_27.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_22 = QtWidgets.QLabel(self.w_End_Cell_Tune_Extra_Variable)
        self.label_22.setMinimumSize(QtCore.QSize(27, 0))
        self.label_22.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_22.setObjectName("label_22")
        self.gridLayout_27.addWidget(self.label_22, 0, 0, 1, 1)
        self.le_Req_i = QtWidgets.QLineEdit(self.w_End_Cell_Tune_Extra_Variable)
        self.le_Req_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Req_i.setObjectName("le_Req_i")
        self.gridLayout_27.addWidget(self.le_Req_i, 0, 1, 1, 1)
        self.gridLayout_25.addWidget(self.w_End_Cell_Tune_Extra_Variable, 5, 1, 1, 2)
        self.widget_8 = QtWidgets.QWidget(self.w_Inner_Cell)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.cb_Inner_Cell = SwitchControl(self.widget_8)
        self.cb_Inner_Cell.setObjectName("cb_Inner_Cell")
        self.gridLayout_9.addWidget(self.cb_Inner_Cell, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_8)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 0, 1, 1, 1)
        self.cb_LBP = SwitchControl(self.widget_8)
        self.cb_LBP.setObjectName("cb_LBP")
        self.gridLayout_9.addWidget(self.cb_LBP, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_8)
        self.label_24.setObjectName("label_24")
        self.gridLayout_9.addWidget(self.label_24, 0, 3, 1, 1)
        self.cb_RBP = SwitchControl(self.widget_8)
        self.cb_RBP.setObjectName("cb_RBP")
        self.gridLayout_9.addWidget(self.cb_RBP, 0, 4, 1, 1)
        self.gridLayout_25.addWidget(self.widget_8, 0, 1, 1, 4)
        self.gridLayout_24.addWidget(self.w_Inner_Cell, 1, 0, 1, 1)
        self.w_Cell_Parameters = QtWidgets.QWidget(self.widget_16)
        self.w_Cell_Parameters.setObjectName("w_Cell_Parameters")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.w_Cell_Parameters)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_35 = QtWidgets.QLabel(self.w_Cell_Parameters)
        self.label_35.setMinimumSize(QtCore.QSize(100, 0))
        self.label_35.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_35.setObjectName("label_35")
        self.gridLayout_17.addWidget(self.label_35, 1, 0, 1, 1)
        self.sb_N_Cells = QtWidgets.QSpinBox(self.w_Cell_Parameters)
        self.sb_N_Cells.setMinimum(1)
        self.sb_N_Cells.setProperty("value", 2)
        self.sb_N_Cells.setObjectName("sb_N_Cells")
        self.gridLayout_17.addWidget(self.sb_N_Cells, 0, 1, 1, 1)
        self.sb_N_Modules = QtWidgets.QSpinBox(self.w_Cell_Parameters)
        self.sb_N_Modules.setProperty("value", 1)
        self.sb_N_Modules.setObjectName("sb_N_Modules")
        self.gridLayout_17.addWidget(self.sb_N_Modules, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.w_Cell_Parameters)
        self.label_31.setMinimumSize(QtCore.QSize(100, 0))
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_31.setObjectName("label_31")
        self.gridLayout_17.addWidget(self.label_31, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.w_Cell_Parameters, 9, 0, 1, 1)
        self.pb_Right_Cell = QtWidgets.QPushButton(self.widget_16)
        self.pb_Right_Cell.setCheckable(True)
        self.pb_Right_Cell.setObjectName("pb_Right_Cell")
        self.gridLayout_24.addWidget(self.pb_Right_Cell, 4, 0, 1, 1)
        self.pb_Mid_Cell = QtWidgets.QPushButton(self.widget_16)
        self.pb_Mid_Cell.setCheckable(True)
        self.pb_Mid_Cell.setChecked(True)
        self.pb_Mid_Cell.setObjectName("pb_Mid_Cell")
        self.gridLayout_24.addWidget(self.pb_Mid_Cell, 0, 0, 1, 1)
        self.pb_Expansion = QtWidgets.QPushButton(self.widget_16)
        self.pb_Expansion.setCheckable(True)
        self.pb_Expansion.setObjectName("pb_Expansion")
        self.gridLayout_24.addWidget(self.pb_Expansion, 6, 0, 1, 1)
        self.pb_Left_Cell = QtWidgets.QPushButton(self.widget_16)
        self.pb_Left_Cell.setCheckable(True)
        self.pb_Left_Cell.setObjectName("pb_Left_Cell")
        self.gridLayout_24.addWidget(self.pb_Left_Cell, 2, 0, 1, 1)
        self.pb_Cell_Parameters = QtWidgets.QPushButton(self.widget_16)
        self.pb_Cell_Parameters.setCheckable(True)
        self.pb_Cell_Parameters.setObjectName("pb_Cell_Parameters")
        self.gridLayout_24.addWidget(self.pb_Cell_Parameters, 8, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_16, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Geometry_Input)
        self.pb_Mid_Cell.toggled['bool'].connect(self.w_Inner_Cell.setVisible)
        self.pb_Cell_Parameters.toggled['bool'].connect(self.w_Cell_Parameters.setVisible)
        self.pb_Left_Cell.toggled['bool'].connect(self.w_Outer_Cell_L.setVisible)
        self.pb_Right_Cell.toggled['bool'].connect(self.w_Outer_Cell_R.setVisible)
        self.pb_Expansion.toggled['bool'].connect(self.w_Expansion.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Geometry_Input)

    def retranslateUi(self, Geometry_Input):
        _translate = QtCore.QCoreApplication.translate
        Geometry_Input.setWindowTitle(_translate("Geometry_Input", "Form"))
        self.cb_Shape_Entry_Mode.setItemText(0, _translate("Geometry_Input", "Load Shape Space"))
        self.cb_Shape_Entry_Mode.setItemText(1, _translate("Geometry_Input", "Enter Shape Manually"))
        self.pb_Select_Shape_Space.setText(_translate("Geometry_Input", "..."))
        self.le_Shape_Space.setText(_translate("Geometry_Input", "test"))
        self.label_33.setText(_translate("Geometry_Input", "c"))
        self.label_28.setText(_translate("Geometry_Input", "Rbp/Lbp"))
        self.label_27.setText(_translate("Geometry_Input", "at"))
        self.label_32.setText(_translate("Geometry_Input", "bt"))
        self.le_Req_or.setText(_translate("Geometry_Input", "345"))
        self.l_Tune_Alternate_Variable_End_Cell_2.setText(_translate("Geometry_Input", "L"))
        self.label_55.setText(_translate("Geometry_Input", "Req"))
        self.le_B_or.setText(_translate("Geometry_Input", "98"))
        self.le_Ri_or.setText(_translate("Geometry_Input", "160"))
        self.le_Alpha_or.setText(_translate("Geometry_Input", "90"))
        self.label_40.setText(_translate("Geometry_Input", "a"))
        self.le_A_or.setText(_translate("Geometry_Input", "110"))
        self.label_38.setText(_translate("Geometry_Input", "Ri"))
        self.label_53.setText(_translate("Geometry_Input", "alp"))
        self.label_48.setText(_translate("Geometry_Input", "B"))
        self.label_45.setText(_translate("Geometry_Input", "A"))
        self.le_L_or.setText(_translate("Geometry_Input", "187"))
        self.le_a_or.setText(_translate("Geometry_Input", "37"))
        self.le_b_or.setText(_translate("Geometry_Input", "28"))
        self.label_39.setText(_translate("Geometry_Input", "b"))
        self.le_Req_ol.setText(_translate("Geometry_Input", "345"))
        self.label_51.setText(_translate("Geometry_Input", "Req"))
        self.label_14.setText(_translate("Geometry_Input", "b"))
        self.label_20.setText(_translate("Geometry_Input", "a"))
        self.le_a_ol.setText(_translate("Geometry_Input", "37"))
        self.le_B_ol.setText(_translate("Geometry_Input", "98"))
        self.le_Alpha_ol.setText(_translate("Geometry_Input", "90"))
        self.le_Ri_ol.setText(_translate("Geometry_Input", "160"))
        self.le_b_ol.setText(_translate("Geometry_Input", "28"))
        self.l_Tune_Alternate_Variable_End_Cell.setText(_translate("Geometry_Input", "L"))
        self.le_L_ol.setText(_translate("Geometry_Input", "187"))
        self.label_26.setText(_translate("Geometry_Input", "B"))
        self.le_A_ol.setText(_translate("Geometry_Input", "110"))
        self.label_5.setText(_translate("Geometry_Input", "Ri"))
        self.label_52.setText(_translate("Geometry_Input", "alp"))
        self.label_25.setText(_translate("Geometry_Input", "A"))
        self.l_Tune_Alternate_Variable.setText(_translate("Geometry_Input", "L"))
        self.le_B_i.setText(_translate("Geometry_Input", "131.75"))
        self.label_49.setText(_translate("Geometry_Input", "alp"))
        self.le_b_i.setText(_translate("Geometry_Input", "118.7"))
        self.le_A_i.setText(_translate("Geometry_Input", "73.52"))
        self.label_6.setText(_translate("Geometry_Input", "A"))
        self.label_8.setText(_translate("Geometry_Input", "a"))
        self.le_a_i.setText(_translate("Geometry_Input", "106.25"))
        self.le_Alpha.setText(_translate("Geometry_Input", "90"))
        self.label_12.setText(_translate("Geometry_Input", "Ri"))
        self.le_L_i.setText(_translate("Geometry_Input", "187"))
        self.label_7.setText(_translate("Geometry_Input", "B"))
        self.label_11.setText(_translate("Geometry_Input", "b"))
        self.le_Ri_i.setText(_translate("Geometry_Input", "150"))
        self.label_22.setText(_translate("Geometry_Input", "Req"))
        self.le_Req_i.setText(_translate("Geometry_Input", "369.632158"))
        self.label_21.setText(_translate("Geometry_Input", "LBP"))
        self.label_24.setText(_translate("Geometry_Input", "RBP"))
        self.label_35.setText(_translate("Geometry_Input", "No. of Modules"))
        self.label_31.setText(_translate("Geometry_Input", "No. of Cells"))
        self.pb_Right_Cell.setText(_translate("Geometry_Input", "Right Cell"))
        self.pb_Mid_Cell.setText(_translate("Geometry_Input", "Inner Cell"))
        self.pb_Expansion.setText(_translate("Geometry_Input", "Expansion"))
        self.pb_Left_Cell.setText(_translate("Geometry_Input", "Left Cell"))
        self.pb_Cell_Parameters.setText(_translate("Geometry_Input", "Cell Parameters"))

from QCheckableComboBox import QCheckableComboBox
from QSwitchControl import SwitchControl

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Geometry_Input = QtWidgets.QWidget()
    ui = Ui_Geometry_Input()
    ui.setupUi(Geometry_Input)
    Geometry_Input.show()
    sys.exit(app.exec_())

