# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/mode_nomenclature.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mode_Nom(object):
    def setupUi(self, Mode_Nom):
        Mode_Nom.setObjectName("Mode_Nom")
        Mode_Nom.resize(935, 618)
        self.gridLayout = QtWidgets.QGridLayout(Mode_Nom)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Mode_Nom)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_rEigenmode = QtWidgets.QPushButton(self.widget_2)
        self.pb_rEigenmode.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_rEigenmode.setMaximumSize(QtCore.QSize(40, 40))
        self.pb_rEigenmode.setStyleSheet("background-color: rgb(216, 74, 255);\n"
"border-style: solid;\n"
"background-color: rgb(216, 74, 255);\n"
"border-width: 5px;\n"
"border-radius: 20px;")
        self.pb_rEigenmode.setText("")
        self.pb_rEigenmode.setObjectName("pb_rEigenmode")
        self.gridLayout_2.addWidget(self.pb_rEigenmode, 0, 1, 1, 1)
        self.pb_rPlot = QtWidgets.QPushButton(self.widget_2)
        self.pb_rPlot.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_rPlot.setMaximumSize(QtCore.QSize(40, 40))
        self.pb_rPlot.setStyleSheet("background-color: rgb(167, 255, 151);\n"
"border-style: solid;\n"
"background-color: rgb(167, 255, 151);\n"
"border-width: 5px;\n"
"border-radius: 20px;")
        self.pb_rPlot.setText("")
        self.pb_rPlot.setObjectName("pb_rPlot")
        self.gridLayout_2.addWidget(self.pb_rPlot, 0, 4, 1, 1)
        self.pb_rPostprocess = QtWidgets.QPushButton(self.widget_2)
        self.pb_rPostprocess.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_rPostprocess.setMaximumSize(QtCore.QSize(40, 40))
        self.pb_rPostprocess.setStyleSheet("background-color: rgb(167, 222, 255);\n"
"border-style: solid;\n"
"background-color: rgb(167, 222, 255);\n"
"border-width: 5px;\n"
"border-radius: 20px;")
        self.pb_rPostprocess.setText("")
        self.pb_rPostprocess.setObjectName("pb_rPostprocess")
        self.gridLayout_2.addWidget(self.pb_rPostprocess, 0, 3, 1, 1)
        self.pb_rWakefield = QtWidgets.QPushButton(self.widget_2)
        self.pb_rWakefield.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_rWakefield.setMaximumSize(QtCore.QSize(40, 40))
        self.pb_rWakefield.setStyleSheet("background-color: rgb(255, 69, 119);\n"
"border-style: solid;\n"
"background-color: rgb(255, 69, 119);\n"
"border-width: 5px;\n"
"border-radius: 20px;")
        self.pb_rWakefield.setText("")
        self.pb_rWakefield.setObjectName("pb_rWakefield")
        self.gridLayout_2.addWidget(self.pb_rWakefield, 0, 2, 1, 1)
        self.pb_ModeNom_rMisc = QtWidgets.QPushButton(self.widget_2)
        self.pb_ModeNom_rMisc.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_ModeNom_rMisc.setMaximumSize(QtCore.QSize(40, 40))
        self.pb_ModeNom_rMisc.setStyleSheet("background-color: gray;\n"
"border-style: solid;\n"
"border-color: gray;\n"
"border-width: 5px;\n"
"border-radius: 20px;")
        self.pb_ModeNom_rMisc.setObjectName("pb_ModeNom_rMisc")
        self.gridLayout_2.addWidget(self.pb_ModeNom_rMisc, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 6, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_3)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 0, 7, 1, 1)
        self.pb_rMisc = QtWidgets.QPushButton(self.widget_2)
        self.pb_rMisc.setMinimumSize(QtCore.QSize(40, 40))
        self.pb_rMisc.setMaximumSize(QtCore.QSize(40, 40))
        self.pb_rMisc.setStyleSheet("background-color: rgb(255, 235, 188);\n"
"border-style: solid;\n"
"background-color: rgb(255, 235, 188);\n"
"border-width: 5px;\n"
"border-radius: 20px;")
        self.pb_rMisc.setText("")
        self.pb_rMisc.setObjectName("pb_rMisc")
        self.gridLayout_2.addWidget(self.pb_rMisc, 0, 5, 1, 1)
        self.gridLayout_3.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pb_Waveguide_Calculations = QtWidgets.QPushButton(self.widget_4)
        self.pb_Waveguide_Calculations.setMinimumSize(QtCore.QSize(150, 150))
        self.pb_Waveguide_Calculations.setMaximumSize(QtCore.QSize(150, 150))
        self.pb_Waveguide_Calculations.setStyleSheet("background-color: rgb(194, 108, 255);")
        self.pb_Waveguide_Calculations.setObjectName("pb_Waveguide_Calculations")
        self.gridLayout_5.addWidget(self.pb_Waveguide_Calculations, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_5.setMinimumSize(QtCore.QSize(150, 150))
        self.pushButton_5.setMaximumSize(QtCore.QSize(150, 150))
        self.pushButton_5.setStyleSheet("background-color: rgb(160, 255, 192);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pb_Mode_Nomenclature = QtWidgets.QPushButton(self.widget_4)
        self.pb_Mode_Nomenclature.setMinimumSize(QtCore.QSize(150, 150))
        self.pb_Mode_Nomenclature.setMaximumSize(QtCore.QSize(150, 150))
        self.pb_Mode_Nomenclature.setStyleSheet("background-color: rgb(255, 167, 66);")
        self.pb_Mode_Nomenclature.setObjectName("pb_Mode_Nomenclature")
        self.gridLayout_5.addWidget(self.pb_Mode_Nomenclature, 2, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.page)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 705, 464))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setMinimumSize(QtCore.QSize(200, 0))
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(200, 100))
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setMinimumSize(QtCore.QSize(200, 100))
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setMinimumSize(QtCore.QSize(200, 100))
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setMinimumSize(QtCore.QSize(200, 100))
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setMinimumSize(QtCore.QSize(200, 100))
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 705, 442))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 705, 442))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 1, 3, 1)
        self.gridLayout_3.addWidget(self.widget_4, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Mode_Nom)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Mode_Nom)

    def retranslateUi(self, Mode_Nom):
        _translate = QtCore.QCoreApplication.translate
        Mode_Nom.setWindowTitle(_translate("Mode_Nom", "Form"))
        self.pb_ModeNom_rMisc.setText(_translate("Mode_Nom", "<--"))
        self.pushButton.setText(_translate("Mode_Nom", "Search"))
        self.pb_Waveguide_Calculations.setText(_translate("Mode_Nom", "CWG"))
        self.pushButton_5.setText(_translate("Mode_Nom", "RWG"))
        self.pb_Mode_Nomenclature.setText(_translate("Mode_Nom", "Elliptical Cavity"))
        self.label_6.setText(_translate("Mode_Nom", "TextLabel"))
        self.label.setText(_translate("Mode_Nom", "TextLabel"))
        self.label_2.setText(_translate("Mode_Nom", "TextLabel"))
        self.label_4.setText(_translate("Mode_Nom", "TextLabel"))
        self.label_3.setText(_translate("Mode_Nom", "TextLabel"))
        self.label_5.setText(_translate("Mode_Nom", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mode_Nom = QtWidgets.QWidget()
    ui = Ui_Mode_Nom()
    ui.setupUi(Mode_Nom)
    Mode_Nom.show()
    sys.exit(app.exec_())
