# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/multipacting.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Multipacting(object):
    def setupUi(self, Multipacting):
        Multipacting.setObjectName("Multipacting")
        Multipacting.resize(1444, 1076)
        self.gridLayout = QtWidgets.QGridLayout(Multipacting)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Multipacting)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -588, 652, 1675))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.w_Multipacting_Solver_Input = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Multipacting_Solver_Input.setObjectName("w_Multipacting_Solver_Input")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.w_Multipacting_Solver_Input)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.w_Multipacting_Solver_Input)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.w_Multipacting_Solver_Input)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.w_Multipacting_Solver_Input)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.w_Multipacting_Solver_Input)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.dsb_Impact_Energy_Min = QtWidgets.QDoubleSpinBox(self.w_Multipacting_Solver_Input)
        self.dsb_Impact_Energy_Min.setObjectName("dsb_Impact_Energy_Min")
        self.gridLayout_3.addWidget(self.dsb_Impact_Energy_Min, 1, 1, 1, 1)
        self.dsb_Impact_Energy_Max = QtWidgets.QDoubleSpinBox(self.w_Multipacting_Solver_Input)
        self.dsb_Impact_Energy_Max.setMinimum(100.0)
        self.dsb_Impact_Energy_Max.setMaximum(999999999999999.0)
        self.dsb_Impact_Energy_Max.setSingleStep(10.0)
        self.dsb_Impact_Energy_Max.setProperty("value", 1000000.0)
        self.dsb_Impact_Energy_Max.setObjectName("dsb_Impact_Energy_Max")
        self.gridLayout_3.addWidget(self.dsb_Impact_Energy_Max, 1, 2, 1, 1)
        self.sb_Number_Of_Impacts = QtWidgets.QSpinBox(self.w_Multipacting_Solver_Input)
        self.sb_Number_Of_Impacts.setMinimum(10)
        self.sb_Number_Of_Impacts.setProperty("value", 20)
        self.sb_Number_Of_Impacts.setObjectName("sb_Number_Of_Impacts")
        self.gridLayout_3.addWidget(self.sb_Number_Of_Impacts, 2, 1, 1, 1)
        self.dsb_Initial_Velocity = QtWidgets.QDoubleSpinBox(self.w_Multipacting_Solver_Input)
        self.dsb_Initial_Velocity.setMinimum(1.0)
        self.dsb_Initial_Velocity.setProperty("value", 2.0)
        self.dsb_Initial_Velocity.setObjectName("dsb_Initial_Velocity")
        self.gridLayout_3.addWidget(self.dsb_Initial_Velocity, 3, 1, 1, 1)
        self.dsb_Reflection_Coeff_Re = QtWidgets.QDoubleSpinBox(self.w_Multipacting_Solver_Input)
        self.dsb_Reflection_Coeff_Re.setObjectName("dsb_Reflection_Coeff_Re")
        self.gridLayout_3.addWidget(self.dsb_Reflection_Coeff_Re, 0, 1, 1, 1)
        self.dsb_Reflection_Coeff_Im = QtWidgets.QDoubleSpinBox(self.w_Multipacting_Solver_Input)
        self.dsb_Reflection_Coeff_Im.setObjectName("dsb_Reflection_Coeff_Im")
        self.gridLayout_3.addWidget(self.dsb_Reflection_Coeff_Im, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.w_Multipacting_Solver_Input, 7, 0, 1, 1)
        self.w_Field_Solver_Input = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Field_Solver_Input.setObjectName("w_Field_Solver_Input")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.w_Field_Solver_Input)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_Frequency_Unit = QtWidgets.QComboBox(self.w_Field_Solver_Input)
        self.cb_Frequency_Unit.setObjectName("cb_Frequency_Unit")
        self.cb_Frequency_Unit.addItem("")
        self.cb_Frequency_Unit.addItem("")
        self.cb_Frequency_Unit.addItem("")
        self.cb_Frequency_Unit.addItem("")
        self.gridLayout_4.addWidget(self.cb_Frequency_Unit, 1, 2, 1, 1)
        self.dsb_Grid_Constant = QtWidgets.QDoubleSpinBox(self.w_Field_Solver_Input)
        self.dsb_Grid_Constant.setMinimum(0.1)
        self.dsb_Grid_Constant.setProperty("value", 3.0)
        self.dsb_Grid_Constant.setObjectName("dsb_Grid_Constant")
        self.gridLayout_4.addWidget(self.dsb_Grid_Constant, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.w_Field_Solver_Input)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.w_Field_Solver_Input)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.w_Field_Solver_Input)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 2, 0, 1, 1)
        self.cb_Geometry_Type = QtWidgets.QComboBox(self.w_Field_Solver_Input)
        self.cb_Geometry_Type.setObjectName("cb_Geometry_Type")
        self.cb_Geometry_Type.addItem("")
        self.cb_Geometry_Type.addItem("")
        self.cb_Geometry_Type.addItem("")
        self.gridLayout_4.addWidget(self.cb_Geometry_Type, 0, 1, 1, 1)
        self.dsb_Frequency = QtWidgets.QDoubleSpinBox(self.w_Field_Solver_Input)
        self.dsb_Frequency.setMinimum(1.0)
        self.dsb_Frequency.setMaximum(1e+24)
        self.dsb_Frequency.setProperty("value", 801.58)
        self.dsb_Frequency.setObjectName("dsb_Frequency")
        self.gridLayout_4.addWidget(self.dsb_Frequency, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.w_Field_Solver_Input)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.w_Field_Solver_Input)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        self.dsb_Mesh_Constant = QtWidgets.QDoubleSpinBox(self.w_Field_Solver_Input)
        self.dsb_Mesh_Constant.setMinimum(0.1)
        self.dsb_Mesh_Constant.setProperty("value", 5.0)
        self.dsb_Mesh_Constant.setObjectName("dsb_Mesh_Constant")
        self.gridLayout_4.addWidget(self.dsb_Mesh_Constant, 4, 1, 1, 1)
        self.dsb_Relative_Epsilon = QtWidgets.QDoubleSpinBox(self.w_Field_Solver_Input)
        self.dsb_Relative_Epsilon.setObjectName("dsb_Relative_Epsilon")
        self.gridLayout_4.addWidget(self.dsb_Relative_Epsilon, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.w_Field_Solver_Input, 5, 0, 1, 1)
        self.pb_Field_Solver_Input = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Field_Solver_Input.setCheckable(True)
        self.pb_Field_Solver_Input.setChecked(True)
        self.pb_Field_Solver_Input.setObjectName("pb_Field_Solver_Input")
        self.gridLayout_5.addWidget(self.pb_Field_Solver_Input, 4, 0, 1, 1)
        self.pb_Geometry_Input = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Geometry_Input.setCheckable(True)
        self.pb_Geometry_Input.setChecked(True)
        self.pb_Geometry_Input.setObjectName("pb_Geometry_Input")
        self.gridLayout_5.addWidget(self.pb_Geometry_Input, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 12, 0, 1, 1)
        self.pb_Multipacting_Solver_Input = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Multipacting_Solver_Input.setCheckable(True)
        self.pb_Multipacting_Solver_Input.setChecked(True)
        self.pb_Multipacting_Solver_Input.setObjectName("pb_Multipacting_Solver_Input")
        self.gridLayout_5.addWidget(self.pb_Multipacting_Solver_Input, 6, 0, 1, 1)
        self.pb_Initial_Sites = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Initial_Sites.setCheckable(True)
        self.pb_Initial_Sites.setChecked(True)
        self.pb_Initial_Sites.setObjectName("pb_Initial_Sites")
        self.gridLayout_5.addWidget(self.pb_Initial_Sites, 8, 0, 1, 1)
        self.pb_Field_Levels = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Field_Levels.setCheckable(True)
        self.pb_Field_Levels.setChecked(True)
        self.pb_Field_Levels.setObjectName("pb_Field_Levels")
        self.gridLayout_5.addWidget(self.pb_Field_Levels, 10, 0, 1, 1)
        self.w_Geometry_Input = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Geometry_Input.setStyleSheet("")
        self.w_Geometry_Input.setObjectName("w_Geometry_Input")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.w_Geometry_Input)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.w_Enter_Geometry_Manual = QtWidgets.QWidget(self.w_Geometry_Input)
        self.w_Enter_Geometry_Manual.setObjectName("w_Enter_Geometry_Manual")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.w_Enter_Geometry_Manual)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.widget_15 = QtWidgets.QWidget(self.w_Enter_Geometry_Manual)
        self.widget_15.setStyleSheet("")
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.cb_Expansion = SwitchControl(self.widget_15)
        self.cb_Expansion.setObjectName("cb_Expansion")
        self.gridLayout_25.addWidget(self.cb_Expansion, 1, 3, 1, 1)
        self.cb_Outer_Cell_L = SwitchControl(self.widget_15)
        self.cb_Outer_Cell_L.setObjectName("cb_Outer_Cell_L")
        self.gridLayout_25.addWidget(self.cb_Outer_Cell_L, 0, 3, 1, 1)
        self.cb_LBP = SwitchControl(self.widget_15)
        self.cb_LBP.setObjectName("cb_LBP")
        self.gridLayout_25.addWidget(self.cb_LBP, 0, 9, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget_15)
        self.label_19.setObjectName("label_19")
        self.gridLayout_25.addWidget(self.label_19, 0, 8, 1, 1)
        self.cb_Inner_Cell = SwitchControl(self.widget_15)
        self.cb_Inner_Cell.setObjectName("cb_Inner_Cell")
        self.gridLayout_25.addWidget(self.cb_Inner_Cell, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_15)
        self.label_15.setObjectName("label_15")
        self.gridLayout_25.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_15)
        self.label_16.setObjectName("label_16")
        self.gridLayout_25.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_15)
        self.label_23.setObjectName("label_23")
        self.gridLayout_25.addWidget(self.label_23, 1, 8, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_15)
        self.label_17.setObjectName("label_17")
        self.gridLayout_25.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_15)
        self.label_18.setObjectName("label_18")
        self.gridLayout_25.addWidget(self.label_18, 1, 2, 1, 1)
        self.cb_RBP = SwitchControl(self.widget_15)
        self.cb_RBP.setObjectName("cb_RBP")
        self.gridLayout_25.addWidget(self.cb_RBP, 1, 9, 1, 1)
        self.cb_Outer_Cell_R = SwitchControl(self.widget_15)
        self.cb_Outer_Cell_R.setObjectName("cb_Outer_Cell_R")
        self.gridLayout_25.addWidget(self.cb_Outer_Cell_R, 1, 1, 1, 1)
        self.gridLayout_24.addWidget(self.widget_15, 0, 0, 1, 1)
        self.w_Expansion = QtWidgets.QWidget(self.w_Enter_Geometry_Manual)
        self.w_Expansion.setMinimumSize(QtCore.QSize(350, 0))
        self.w_Expansion.setMaximumSize(QtCore.QSize(350, 16777215))
        self.w_Expansion.setStyleSheet("#w_Expansion{border-radius: 15px;}")
        self.w_Expansion.setObjectName("w_Expansion")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.w_Expansion)
        self.gridLayout_30.setObjectName("gridLayout_30")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem1, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.w_Expansion)
        self.label_27.setMinimumSize(QtCore.QSize(25, 0))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_30.addWidget(self.label_27, 0, 0, 1, 1)
        self.le_a_t = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_a_t.setMinimumSize(QtCore.QSize(75, 0))
        self.le_a_t.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_a_t.setObjectName("le_a_t")
        self.gridLayout_30.addWidget(self.le_a_t, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.w_Expansion)
        self.label_28.setMinimumSize(QtCore.QSize(25, 0))
        self.label_28.setObjectName("label_28")
        self.gridLayout_30.addWidget(self.label_28, 0, 6, 1, 1)
        self.le_Rbp_Lbp = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_Rbp_Lbp.setMinimumSize(QtCore.QSize(75, 0))
        self.le_Rbp_Lbp.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_Rbp_Lbp.setObjectName("le_Rbp_Lbp")
        self.gridLayout_30.addWidget(self.le_Rbp_Lbp, 0, 7, 1, 1)
        self.le_b_t = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_b_t.setMinimumSize(QtCore.QSize(75, 0))
        self.le_b_t.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_b_t.setObjectName("le_b_t")
        self.gridLayout_30.addWidget(self.le_b_t, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.w_Expansion)
        self.label_32.setMinimumSize(QtCore.QSize(25, 0))
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_30.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.w_Expansion)
        self.label_33.setMinimumSize(QtCore.QSize(25, 0))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_30.addWidget(self.label_33, 2, 0, 1, 1)
        self.le_c = QtWidgets.QLineEdit(self.w_Expansion)
        self.le_c.setMinimumSize(QtCore.QSize(75, 0))
        self.le_c.setMaximumSize(QtCore.QSize(75, 16777215))
        self.le_c.setObjectName("le_c")
        self.gridLayout_30.addWidget(self.le_c, 2, 1, 1, 1)
        self.gridLayout_24.addWidget(self.w_Expansion, 4, 0, 1, 1)
        self.w_Outer_Cell_L = QtWidgets.QWidget(self.w_Enter_Geometry_Manual)
        self.w_Outer_Cell_L.setStyleSheet("#w_Outer_Cell_L{border-radius: 15px;}")
        self.w_Outer_Cell_L.setObjectName("w_Outer_Cell_L")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.w_Outer_Cell_L)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.label_39 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_39.setMinimumSize(QtCore.QSize(25, 0))
        self.label_39.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_28.addWidget(self.label_39, 0, 0, 1, 1)
        self.le_Ri_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_Ri_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Ri_ol.setObjectName("le_Ri_ol")
        self.gridLayout_28.addWidget(self.le_Ri_ol, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_25.setMinimumSize(QtCore.QSize(25, 0))
        self.label_25.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_28.addWidget(self.label_25, 3, 0, 1, 1)
        self.le_Alpha_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_Alpha_ol.setObjectName("le_Alpha_ol")
        self.gridLayout_28.addWidget(self.le_Alpha_ol, 4, 3, 1, 1)
        self.le_L_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_L_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_L_ol.setObjectName("le_L_ol")
        self.gridLayout_28.addWidget(self.le_L_ol, 3, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_51.setObjectName("label_51")
        self.gridLayout_28.addWidget(self.label_51, 4, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_52.setObjectName("label_52")
        self.gridLayout_28.addWidget(self.label_52, 4, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_38.setMinimumSize(QtCore.QSize(25, 0))
        self.label_38.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_28.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_20.setMinimumSize(QtCore.QSize(25, 0))
        self.label_20.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_28.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.label_26.setMinimumSize(QtCore.QSize(25, 0))
        self.label_26.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_28.addWidget(self.label_26, 2, 2, 1, 1)
        self.le_Req_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_Req_ol.setReadOnly(True)
        self.le_Req_ol.setObjectName("le_Req_ol")
        self.gridLayout_28.addWidget(self.le_Req_ol, 4, 1, 1, 1)
        self.le_a_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_a_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_a_ol.setObjectName("le_a_ol")
        self.gridLayout_28.addWidget(self.le_a_ol, 2, 1, 1, 1)
        self.le_b_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_b_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_b_ol.setObjectName("le_b_ol")
        self.gridLayout_28.addWidget(self.le_b_ol, 2, 3, 1, 1)
        self.l_Tune_Alternate_Variable_End_Cell = QtWidgets.QLabel(self.w_Outer_Cell_L)
        self.l_Tune_Alternate_Variable_End_Cell.setMinimumSize(QtCore.QSize(25, 0))
        self.l_Tune_Alternate_Variable_End_Cell.setMaximumSize(QtCore.QSize(25, 16777215))
        self.l_Tune_Alternate_Variable_End_Cell.setAlignment(QtCore.Qt.AlignCenter)
        self.l_Tune_Alternate_Variable_End_Cell.setObjectName("l_Tune_Alternate_Variable_End_Cell")
        self.gridLayout_28.addWidget(self.l_Tune_Alternate_Variable_End_Cell, 3, 2, 1, 1)
        self.le_A_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_A_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_A_ol.setObjectName("le_A_ol")
        self.gridLayout_28.addWidget(self.le_A_ol, 0, 1, 1, 1)
        self.le_B_ol = QtWidgets.QLineEdit(self.w_Outer_Cell_L)
        self.le_B_ol.setMinimumSize(QtCore.QSize(70, 0))
        self.le_B_ol.setObjectName("le_B_ol")
        self.gridLayout_28.addWidget(self.le_B_ol, 0, 3, 1, 1)
        self.gridLayout_24.addWidget(self.w_Outer_Cell_L, 2, 0, 1, 1)
        self.w_Outer_Cell_R = QtWidgets.QWidget(self.w_Enter_Geometry_Manual)
        self.w_Outer_Cell_R.setStyleSheet("#w_Outer_Cell_R{border-radius: 15px;}")
        self.w_Outer_Cell_R.setObjectName("w_Outer_Cell_R")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.w_Outer_Cell_R)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.le_Req_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_Req_or.setReadOnly(True)
        self.le_Req_or.setObjectName("le_Req_or")
        self.gridLayout_33.addWidget(self.le_Req_or, 4, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_61.setMinimumSize(QtCore.QSize(25, 0))
        self.label_61.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.gridLayout_33.addWidget(self.label_61, 3, 0, 1, 1)
        self.le_a_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_a_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_a_or.setObjectName("le_a_or")
        self.gridLayout_33.addWidget(self.le_a_or, 2, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_62.setMinimumSize(QtCore.QSize(25, 0))
        self.label_62.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_33.addWidget(self.label_62, 0, 0, 1, 1)
        self.le_Ri_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_Ri_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Ri_or.setObjectName("le_Ri_or")
        self.gridLayout_33.addWidget(self.le_Ri_or, 3, 1, 1, 1)
        self.le_A_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_A_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_A_or.setObjectName("le_A_or")
        self.gridLayout_33.addWidget(self.le_A_or, 0, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_60.setMinimumSize(QtCore.QSize(25, 0))
        self.label_60.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_33.addWidget(self.label_60, 0, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_59.setObjectName("label_59")
        self.gridLayout_33.addWidget(self.label_59, 4, 2, 1, 1)
        self.l_Tune_Alternate_Variable_End_Cell_2 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.l_Tune_Alternate_Variable_End_Cell_2.setMinimumSize(QtCore.QSize(25, 0))
        self.l_Tune_Alternate_Variable_End_Cell_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.l_Tune_Alternate_Variable_End_Cell_2.setAlignment(QtCore.Qt.AlignCenter)
        self.l_Tune_Alternate_Variable_End_Cell_2.setObjectName("l_Tune_Alternate_Variable_End_Cell_2")
        self.gridLayout_33.addWidget(self.l_Tune_Alternate_Variable_End_Cell_2, 3, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_64.setMinimumSize(QtCore.QSize(25, 0))
        self.label_64.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_33.addWidget(self.label_64, 2, 2, 1, 1)
        self.le_B_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_B_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_B_or.setObjectName("le_B_or")
        self.gridLayout_33.addWidget(self.le_B_or, 0, 3, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_63.setMinimumSize(QtCore.QSize(25, 0))
        self.label_63.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_33.addWidget(self.label_63, 2, 0, 1, 1)
        self.le_b_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_b_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_b_or.setObjectName("le_b_or")
        self.gridLayout_33.addWidget(self.le_b_or, 2, 3, 1, 1)
        self.le_Alpha_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_Alpha_or.setObjectName("le_Alpha_or")
        self.gridLayout_33.addWidget(self.le_Alpha_or, 4, 3, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.w_Outer_Cell_R)
        self.label_65.setObjectName("label_65")
        self.gridLayout_33.addWidget(self.label_65, 4, 0, 1, 1)
        self.le_L_or = QtWidgets.QLineEdit(self.w_Outer_Cell_R)
        self.le_L_or.setMinimumSize(QtCore.QSize(70, 0))
        self.le_L_or.setObjectName("le_L_or")
        self.gridLayout_33.addWidget(self.le_L_or, 3, 3, 1, 1)
        self.gridLayout_24.addWidget(self.w_Outer_Cell_R, 3, 0, 1, 1)
        self.w_Inner_Cell = QtWidgets.QWidget(self.w_Enter_Geometry_Manual)
        self.w_Inner_Cell.setStyleSheet("#w_Inner_Cell{border-radius: 15px;}")
        self.w_Inner_Cell.setObjectName("w_Inner_Cell")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.w_Inner_Cell)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_44 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_44.setMinimumSize(QtCore.QSize(25, 0))
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_27.addWidget(self.label_44, 2, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_45.setMinimumSize(QtCore.QSize(25, 0))
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_27.addWidget(self.label_45, 0, 3, 1, 1)
        self.l_Tune_Alternate_Variable = QtWidgets.QLabel(self.w_Inner_Cell)
        self.l_Tune_Alternate_Variable.setMinimumSize(QtCore.QSize(25, 0))
        self.l_Tune_Alternate_Variable.setMaximumSize(QtCore.QSize(30, 16777215))
        self.l_Tune_Alternate_Variable.setAlignment(QtCore.Qt.AlignCenter)
        self.l_Tune_Alternate_Variable.setObjectName("l_Tune_Alternate_Variable")
        self.gridLayout_27.addWidget(self.l_Tune_Alternate_Variable, 3, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_48.setMinimumSize(QtCore.QSize(27, 0))
        self.label_48.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.gridLayout_27.addWidget(self.label_48, 3, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_53.setMinimumSize(QtCore.QSize(27, 0))
        self.label_53.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.gridLayout_27.addWidget(self.label_53, 0, 1, 1, 1)
        self.le_Ri_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_Ri_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Ri_i.setObjectName("le_Ri_i")
        self.gridLayout_27.addWidget(self.le_Ri_i, 3, 2, 1, 1)
        self.le_L_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_L_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_L_i.setObjectName("le_L_i")
        self.gridLayout_27.addWidget(self.le_L_i, 3, 4, 1, 1)
        self.le_A_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_A_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_A_i.setObjectName("le_A_i")
        self.gridLayout_27.addWidget(self.le_A_i, 0, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_55.setMinimumSize(QtCore.QSize(27, 0))
        self.label_55.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_27.addWidget(self.label_55, 2, 1, 1, 1)
        self.le_b_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_b_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_b_i.setObjectName("le_b_i")
        self.gridLayout_27.addWidget(self.le_b_i, 2, 4, 1, 1)
        self.le_Alpha = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_Alpha.setObjectName("le_Alpha")
        self.gridLayout_27.addWidget(self.le_Alpha, 4, 4, 1, 1)
        self.le_a_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_a_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_a_i.setObjectName("le_a_i")
        self.gridLayout_27.addWidget(self.le_a_i, 2, 2, 1, 1)
        self.le_B_i = QtWidgets.QLineEdit(self.w_Inner_Cell)
        self.le_B_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_B_i.setObjectName("le_B_i")
        self.gridLayout_27.addWidget(self.le_B_i, 0, 4, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.w_Inner_Cell)
        self.label_49.setObjectName("label_49")
        self.gridLayout_27.addWidget(self.label_49, 4, 3, 1, 1)
        self.w_End_Cell_Tune_Extra_Variable = QtWidgets.QWidget(self.w_Inner_Cell)
        self.w_End_Cell_Tune_Extra_Variable.setObjectName("w_End_Cell_Tune_Extra_Variable")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.w_End_Cell_Tune_Extra_Variable)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.label_57 = QtWidgets.QLabel(self.w_End_Cell_Tune_Extra_Variable)
        self.label_57.setMinimumSize(QtCore.QSize(27, 0))
        self.label_57.setMaximumSize(QtCore.QSize(27, 16777215))
        self.label_57.setObjectName("label_57")
        self.gridLayout_32.addWidget(self.label_57, 0, 0, 1, 1)
        self.le_Req_i = QtWidgets.QLineEdit(self.w_End_Cell_Tune_Extra_Variable)
        self.le_Req_i.setMinimumSize(QtCore.QSize(70, 0))
        self.le_Req_i.setObjectName("le_Req_i")
        self.gridLayout_32.addWidget(self.le_Req_i, 0, 1, 1, 1)
        self.gridLayout_27.addWidget(self.w_End_Cell_Tune_Extra_Variable, 4, 1, 1, 2)
        self.gridLayout_24.addWidget(self.w_Inner_Cell, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.w_Enter_Geometry_Manual, 1, 0, 1, 1)
        self.w_Load_Manual = QtWidgets.QWidget(self.w_Geometry_Input)
        self.w_Load_Manual.setMaximumSize(QtCore.QSize(700, 16777215))
        self.w_Load_Manual.setStyleSheet("border-radius: 15px;")
        self.w_Load_Manual.setObjectName("w_Load_Manual")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.w_Load_Manual)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.cb_Shape_Entry_Mode = QtWidgets.QComboBox(self.w_Load_Manual)
        self.cb_Shape_Entry_Mode.setObjectName("cb_Shape_Entry_Mode")
        self.cb_Shape_Entry_Mode.addItem("")
        self.cb_Shape_Entry_Mode.addItem("")
        self.gridLayout_35.addWidget(self.cb_Shape_Entry_Mode, 0, 0, 1, 1)
        self.w_Select_Shape_Space = QtWidgets.QWidget(self.w_Load_Manual)
        self.w_Select_Shape_Space.setObjectName("w_Select_Shape_Space")
        self.gridLayout_86 = QtWidgets.QGridLayout(self.w_Select_Shape_Space)
        self.gridLayout_86.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_86.setObjectName("gridLayout_86")
        self.pb_Select_Shape_Space = QtWidgets.QPushButton(self.w_Select_Shape_Space)
        self.pb_Select_Shape_Space.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pb_Select_Shape_Space.setObjectName("pb_Select_Shape_Space")
        self.gridLayout_86.addWidget(self.pb_Select_Shape_Space, 0, 2, 1, 1)
        self.le_Shape_Space = QtWidgets.QLineEdit(self.w_Select_Shape_Space)
        self.le_Shape_Space.setPlaceholderText("")
        self.le_Shape_Space.setObjectName("le_Shape_Space")
        self.gridLayout_86.addWidget(self.le_Shape_Space, 0, 0, 1, 1)
        self.cb_Shape_Space_Keys = QCheckableComboBox(self.w_Select_Shape_Space)
        self.cb_Shape_Space_Keys.setObjectName("cb_Shape_Space_Keys")
        self.gridLayout_86.addWidget(self.cb_Shape_Space_Keys, 0, 1, 1, 1)
        self.gridLayout_35.addWidget(self.w_Select_Shape_Space, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.w_Load_Manual, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_5.addWidget(self.w_Geometry_Input, 2, 0, 1, 1)
        self.w_Field_Levels = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Field_Levels.setObjectName("w_Field_Levels")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.w_Field_Levels)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dsb_Field_Levels_Min = QtWidgets.QDoubleSpinBox(self.w_Field_Levels)
        self.dsb_Field_Levels_Min.setMinimum(1000.0)
        self.dsb_Field_Levels_Min.setMaximum(999999999999999.0)
        self.dsb_Field_Levels_Min.setObjectName("dsb_Field_Levels_Min")
        self.gridLayout_8.addWidget(self.dsb_Field_Levels_Min, 0, 1, 1, 1)
        self.dsb_Field_Levels_Max = QtWidgets.QDoubleSpinBox(self.w_Field_Levels)
        self.dsb_Field_Levels_Max.setMinimum(60000.0)
        self.dsb_Field_Levels_Max.setMaximum(999999999999.0)
        self.dsb_Field_Levels_Max.setObjectName("dsb_Field_Levels_Max")
        self.gridLayout_8.addWidget(self.dsb_Field_Levels_Max, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.w_Field_Levels)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.w_Field_Levels)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 0, 0, 1, 1)
        self.dsb_Field_Levels_Step = QtWidgets.QDoubleSpinBox(self.w_Field_Levels)
        self.dsb_Field_Levels_Step.setMinimum(500.0)
        self.dsb_Field_Levels_Step.setMaximum(999999999999999.0)
        self.dsb_Field_Levels_Step.setObjectName("dsb_Field_Levels_Step")
        self.gridLayout_8.addWidget(self.dsb_Field_Levels_Step, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.w_Field_Levels)
        self.label_22.setObjectName("label_22")
        self.gridLayout_8.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.w_Field_Levels)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.w_Field_Levels)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.w_Field_Levels)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 2, 2, 1, 1)
        self.gridLayout_5.addWidget(self.w_Field_Levels, 11, 0, 1, 1)
        self.w_Initial_Sites = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Initial_Sites.setObjectName("w_Initial_Sites")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.w_Initial_Sites)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_10 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.dsb_Initial_Sites_Phase_Step = QtWidgets.QDoubleSpinBox(self.w_Initial_Sites)
        self.dsb_Initial_Sites_Phase_Step.setObjectName("dsb_Initial_Sites_Phase_Step")
        self.gridLayout_7.addWidget(self.dsb_Initial_Sites_Phase_Step, 0, 1, 1, 1)
        self.dsb_Initial_Sites_Step = QtWidgets.QDoubleSpinBox(self.w_Initial_Sites)
        self.dsb_Initial_Sites_Step.setObjectName("dsb_Initial_Sites_Step")
        self.gridLayout_7.addWidget(self.dsb_Initial_Sites_Step, 2, 1, 1, 1)
        self.dsb_Initial_Sites_Min = QtWidgets.QDoubleSpinBox(self.w_Initial_Sites)
        self.dsb_Initial_Sites_Min.setObjectName("dsb_Initial_Sites_Min")
        self.gridLayout_7.addWidget(self.dsb_Initial_Sites_Min, 1, 1, 1, 1)
        self.dsb_Initial_Sites_Max = QtWidgets.QDoubleSpinBox(self.w_Initial_Sites)
        self.dsb_Initial_Sites_Max.setObjectName("dsb_Initial_Sites_Max")
        self.gridLayout_7.addWidget(self.dsb_Initial_Sites_Max, 3, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_31.setObjectName("label_31")
        self.gridLayout_7.addWidget(self.label_31, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_34.setObjectName("label_34")
        self.gridLayout_7.addWidget(self.label_34, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_35.setObjectName("label_35")
        self.gridLayout_7.addWidget(self.label_35, 3, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.w_Initial_Sites)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.w_Initial_Sites, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 13, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pb_Coupler_Defaults = QtWidgets.QPushButton(self.widget_2)
        self.pb_Coupler_Defaults.setObjectName("pb_Coupler_Defaults")
        self.gridLayout_11.addWidget(self.pb_Coupler_Defaults, 0, 1, 1, 1)
        self.pb_Show_Points = QtWidgets.QPushButton(self.widget_2)
        self.pb_Show_Points.setObjectName("pb_Show_Points")
        self.gridLayout_11.addWidget(self.pb_Show_Points, 0, 3, 1, 1)
        self.pb_Window_Defaults = QtWidgets.QPushButton(self.widget_2)
        self.pb_Window_Defaults.setObjectName("pb_Window_Defaults")
        self.gridLayout_11.addWidget(self.pb_Window_Defaults, 0, 2, 1, 1)
        self.pb_Cavity_Defaults = QtWidgets.QPushButton(self.widget_2)
        self.pb_Cavity_Defaults.setObjectName("pb_Cavity_Defaults")
        self.gridLayout_11.addWidget(self.pb_Cavity_Defaults, 0, 0, 1, 1)
        self.pb_Save = QtWidgets.QPushButton(self.widget_2)
        self.pb_Save.setObjectName("pb_Save")
        self.gridLayout_11.addWidget(self.pb_Save, 0, 4, 1, 1)
        self.gridLayout_5.addWidget(self.widget_2, 3, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pb_Run = QtWidgets.QPushButton(self.widget_3)
        self.pb_Run.setObjectName("pb_Run")
        self.gridLayout_9.addWidget(self.pb_Run, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.widget_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.w_Display = QtWidgets.QWidget(self.splitter)
        self.w_Display.setObjectName("w_Display")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.w_Display)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.tw_Display = QtWidgets.QTabWidget(self.w_Display)
        self.tw_Display.setObjectName("tw_Display")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gl_Plot_Area = QtWidgets.QGridLayout()
        self.gl_Plot_Area.setObjectName("gl_Plot_Area")
        self.gridLayout_12.addLayout(self.gl_Plot_Area, 0, 0, 1, 1)
        self.tw_Display.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gl_Display_3D = QtWidgets.QGridLayout()
        self.gl_Display_3D.setObjectName("gl_Display_3D")
        self.gridLayout_13.addLayout(self.gl_Display_3D, 0, 0, 1, 1)
        self.tw_Display.addTab(self.tab_2, "")
        self.gridLayout_10.addWidget(self.tw_Display, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.retranslateUi(Multipacting)
        self.tw_Display.setCurrentIndex(0)
        self.pb_Field_Solver_Input.toggled['bool'].connect(self.w_Field_Solver_Input.setVisible)
        self.pb_Multipacting_Solver_Input.toggled['bool'].connect(self.w_Multipacting_Solver_Input.setVisible)
        self.pb_Initial_Sites.toggled['bool'].connect(self.w_Initial_Sites.setVisible)
        self.pb_Field_Levels.toggled['bool'].connect(self.w_Field_Levels.setVisible)
        self.pb_Geometry_Input.toggled['bool'].connect(self.w_Geometry_Input.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Multipacting)

    def retranslateUi(self, Multipacting):
        _translate = QtCore.QCoreApplication.translate
        Multipacting.setWindowTitle(_translate("Multipacting", "Form"))
        self.label.setText(_translate("Multipacting", "Reflection Coefficient"))
        self.label_8.setText(_translate("Multipacting", "Number of Impacts"))
        self.label_9.setText(_translate("Multipacting", "Initial Velocity"))
        self.label_7.setText(_translate("Multipacting", "Impact Energy"))
        self.cb_Frequency_Unit.setItemText(0, _translate("Multipacting", "MHz"))
        self.cb_Frequency_Unit.setItemText(1, _translate("Multipacting", "GHz"))
        self.cb_Frequency_Unit.setItemText(2, _translate("Multipacting", "kHz"))
        self.cb_Frequency_Unit.setItemText(3, _translate("Multipacting", "Hz"))
        self.label_2.setText(_translate("Multipacting", "Geometry Type"))
        self.label_3.setText(_translate("Multipacting", "Frequency [GHz]"))
        self.label_4.setText(_translate("Multipacting", "Relative Epsilon"))
        self.cb_Geometry_Type.setItemText(0, _translate("Multipacting", "Cavity"))
        self.cb_Geometry_Type.setItemText(1, _translate("Multipacting", "Coupler"))
        self.cb_Geometry_Type.setItemText(2, _translate("Multipacting", "Window"))
        self.label_6.setText(_translate("Multipacting", "Mesh Constant"))
        self.label_5.setText(_translate("Multipacting", "Grid Constant"))
        self.pb_Field_Solver_Input.setText(_translate("Multipacting", "Field Solver Input"))
        self.pb_Geometry_Input.setText(_translate("Multipacting", "Geometry Input"))
        self.pb_Multipacting_Solver_Input.setText(_translate("Multipacting", "Multipacting Solver Input"))
        self.pb_Initial_Sites.setText(_translate("Multipacting", "Initial Sites"))
        self.pb_Field_Levels.setText(_translate("Multipacting", "Field Levels"))
        self.label_19.setText(_translate("Multipacting", "Left Beampipe"))
        self.label_15.setText(_translate("Multipacting", "Mid Cell"))
        self.label_16.setText(_translate("Multipacting", "Left Cell"))
        self.label_23.setText(_translate("Multipacting", "Right Beampipe"))
        self.label_17.setText(_translate("Multipacting", "Right Cell"))
        self.label_18.setText(_translate("Multipacting", "Expansion"))
        self.label_27.setText(_translate("Multipacting", "at"))
        self.label_28.setText(_translate("Multipacting", "Rbp/Lbp"))
        self.label_32.setText(_translate("Multipacting", "bt"))
        self.label_33.setText(_translate("Multipacting", "c"))
        self.label_39.setText(_translate("Multipacting", "A"))
        self.le_Ri_ol.setText(_translate("Multipacting", "160"))
        self.label_25.setText(_translate("Multipacting", "Ri"))
        self.le_Alpha_ol.setText(_translate("Multipacting", "90"))
        self.le_L_ol.setText(_translate("Multipacting", "187"))
        self.label_51.setText(_translate("Multipacting", "Req"))
        self.label_52.setText(_translate("Multipacting", "alp"))
        self.label_38.setText(_translate("Multipacting", "B"))
        self.label_20.setText(_translate("Multipacting", "a"))
        self.label_26.setText(_translate("Multipacting", "b"))
        self.le_Req_ol.setText(_translate("Multipacting", "345"))
        self.le_a_ol.setText(_translate("Multipacting", "37"))
        self.le_b_ol.setText(_translate("Multipacting", "28"))
        self.l_Tune_Alternate_Variable_End_Cell.setText(_translate("Multipacting", "L"))
        self.le_A_ol.setText(_translate("Multipacting", "110"))
        self.le_B_ol.setText(_translate("Multipacting", "98"))
        self.le_Req_or.setText(_translate("Multipacting", "345"))
        self.label_61.setText(_translate("Multipacting", "Ri"))
        self.le_a_or.setText(_translate("Multipacting", "37"))
        self.label_62.setText(_translate("Multipacting", "A"))
        self.le_Ri_or.setText(_translate("Multipacting", "160"))
        self.le_A_or.setText(_translate("Multipacting", "110"))
        self.label_60.setText(_translate("Multipacting", "B"))
        self.label_59.setText(_translate("Multipacting", "alp"))
        self.l_Tune_Alternate_Variable_End_Cell_2.setText(_translate("Multipacting", "L"))
        self.label_64.setText(_translate("Multipacting", "b"))
        self.le_B_or.setText(_translate("Multipacting", "98"))
        self.label_63.setText(_translate("Multipacting", "a"))
        self.le_b_or.setText(_translate("Multipacting", "28"))
        self.le_Alpha_or.setText(_translate("Multipacting", "90"))
        self.label_65.setText(_translate("Multipacting", "Req"))
        self.le_L_or.setText(_translate("Multipacting", "187"))
        self.label_44.setText(_translate("Multipacting", "b"))
        self.label_45.setText(_translate("Multipacting", "B"))
        self.l_Tune_Alternate_Variable.setText(_translate("Multipacting", "L"))
        self.label_48.setText(_translate("Multipacting", "Ri"))
        self.label_53.setText(_translate("Multipacting", "A"))
        self.le_Ri_i.setText(_translate("Multipacting", "150"))
        self.le_L_i.setText(_translate("Multipacting", "187"))
        self.le_A_i.setText(_translate("Multipacting", "120"))
        self.label_55.setText(_translate("Multipacting", "a"))
        self.le_b_i.setText(_translate("Multipacting", "40"))
        self.le_Alpha.setText(_translate("Multipacting", "90"))
        self.le_a_i.setText(_translate("Multipacting", "45"))
        self.le_B_i.setText(_translate("Multipacting", "100"))
        self.label_49.setText(_translate("Multipacting", "alp"))
        self.label_57.setText(_translate("Multipacting", "Req"))
        self.le_Req_i.setText(_translate("Multipacting", "345"))
        self.cb_Shape_Entry_Mode.setItemText(0, _translate("Multipacting", "Load Shape Space"))
        self.cb_Shape_Entry_Mode.setItemText(1, _translate("Multipacting", "Enter Shape Manually"))
        self.pb_Select_Shape_Space.setText(_translate("Multipacting", "..."))
        self.le_Shape_Space.setText(_translate("Multipacting", "test"))
        self.label_21.setText(_translate("Multipacting", "step"))
        self.label_14.setText(_translate("Multipacting", "min"))
        self.label_22.setText(_translate("Multipacting", "max"))
        self.label_24.setText(_translate("Multipacting", "[kV/m]/[kW]"))
        self.label_29.setText(_translate("Multipacting", "[kV/m]/[kW]"))
        self.label_30.setText(_translate("Multipacting", "[kV/m]/[kW]"))
        self.label_10.setText(_translate("Multipacting", "Phase step"))
        self.label_11.setText(_translate("Multipacting", "min z"))
        self.label_12.setText(_translate("Multipacting", "Space step"))
        self.label_13.setText(_translate("Multipacting", "max z"))
        self.label_31.setText(_translate("Multipacting", "[m]"))
        self.label_34.setText(_translate("Multipacting", "[m]"))
        self.label_35.setText(_translate("Multipacting", "[m]"))
        self.label_36.setText(_translate("Multipacting", "[deg]"))
        self.pb_Coupler_Defaults.setText(_translate("Multipacting", "Coupler Defaults"))
        self.pb_Show_Points.setText(_translate("Multipacting", "Show Points"))
        self.pb_Window_Defaults.setText(_translate("Multipacting", "Window Defaults"))
        self.pb_Cavity_Defaults.setText(_translate("Multipacting", "Cavity Defaults"))
        self.pb_Save.setText(_translate("Multipacting", "Save"))
        self.pb_Run.setText(_translate("Multipacting", "Run"))
        self.tw_Display.setTabText(self.tw_Display.indexOf(self.tab), _translate("Multipacting", "2D"))
        self.tw_Display.setTabText(self.tw_Display.indexOf(self.tab_2), _translate("Multipacting", "3D"))

from QCheckableComboBox import QCheckableComboBox
from QSwitchControl import SwitchControl

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Multipacting = QtWidgets.QWidget()
    ui = Ui_Multipacting()
    ui.setupUi(Multipacting)
    Multipacting.show()
    sys.exit(app.exec_())

