# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/pandas_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PandasTV(object):
    def setupUi(self, PandasTV):
        PandasTV.setObjectName("PandasTV")
        PandasTV.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(PandasTV)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_7 = QtWidgets.QWidget(PandasTV)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.tv_Pandas = QtWidgets.QTableView(self.widget_7)
        self.tv_Pandas.setObjectName("tv_Pandas")
        self.gridLayout_16.addWidget(self.tv_Pandas, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_7, 0, 0, 1, 1)

        self.retranslateUi(PandasTV)
        QtCore.QMetaObject.connectSlotsByName(PandasTV)

    def retranslateUi(self, PandasTV):
        _translate = QtCore.QCoreApplication.translate
        PandasTV.setWindowTitle(_translate("PandasTV", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PandasTV = QtWidgets.QWidget()
    ui = Ui_PandasTV()
    ui.setupUi(PandasTV)
    PandasTV.show()
    sys.exit(app.exec_())
