# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/plot_widget_header.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Header(object):
    def setupUi(self, Header):
        Header.setObjectName("Header")
        Header.resize(266, 122)
        self.gridLayout = QtWidgets.QGridLayout(Header)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(Header)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pb_Drop = QtWidgets.QPushButton(self.widget_2)
        self.pb_Drop.setMinimumSize(QtCore.QSize(20, 25))
        self.pb_Drop.setMaximumSize(QtCore.QSize(20, 25))
        self.pb_Drop.setCheckable(True)
        self.pb_Drop.setObjectName("pb_Drop")
        self.gridLayout_2.addWidget(self.pb_Drop, 1, 3, 1, 1)
        self.pb_Load = QtWidgets.QPushButton(self.widget_2)
        self.pb_Load.setMinimumSize(QtCore.QSize(30, 25))
        self.pb_Load.setMaximumSize(QtCore.QSize(30, 25))
        self.pb_Load.setObjectName("pb_Load")
        self.gridLayout_2.addWidget(self.pb_Load, 1, 1, 1, 1)
        self.switchControl = SwitchControl(self.widget_2)
        self.switchControl.setObjectName("switchControl")
        self.gridLayout_2.addWidget(self.switchControl, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)
        self.cb_Type = QtWidgets.QComboBox(self.widget_2)
        self.cb_Type.setMinimumSize(QtCore.QSize(100, 0))
        self.cb_Type.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cb_Type.setObjectName("cb_Type")
        self.cb_Type.addItem("")
        self.cb_Type.addItem("")
        self.cb_Type.addItem("")
        self.cb_Type.addItem("")
        self.cb_Type.addItem("")
        self.gridLayout_2.addWidget(self.cb_Type, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(Header)
        QtCore.QMetaObject.connectSlotsByName(Header)

    def retranslateUi(self, Header):
        _translate = QtCore.QCoreApplication.translate
        Header.setWindowTitle(_translate("Header", "Form"))
        self.pb_Drop.setText(_translate("Header", "v"))
        self.pb_Load.setText(_translate("Header", "..."))
        self.label.setText(_translate("Header", "Filename"))
        self.cb_Type.setItemText(0, _translate("Header", "abci"))
        self.cb_Type.setItemText(1, _translate("Header", "slans"))
        self.cb_Type.setItemText(2, _translate("Header", "excel"))
        self.cb_Type.setItemText(3, _translate("Header", "txt"))
        self.cb_Type.setItemText(4, _translate("Header", "svl"))
from QSwitchControl import SwitchControl


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Header = QtWidgets.QWidget()
    ui = Ui_Header()
    ui.setupUi(Header)
    Header.show()
    sys.exit(app.exec_())
