# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/pp_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PPPlot(object):
    def setupUi(self, PPPlot):
        PPPlot.setObjectName("PPPlot")
        PPPlot.resize(667, 300)
        self.gridLayout = QtWidgets.QGridLayout(PPPlot)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_16 = QtWidgets.QWidget(PPPlot)
        self.widget_16.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.gl_Plot_Area = QtWidgets.QGridLayout()
        self.gl_Plot_Area.setObjectName("gl_Plot_Area")
        self.gridLayout_28.addLayout(self.gl_Plot_Area, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.widget_16, 0, 0, 1, 1)

        self.retranslateUi(PPPlot)
        QtCore.QMetaObject.connectSlotsByName(PPPlot)

    def retranslateUi(self, PPPlot):
        _translate = QtCore.QCoreApplication.translate
        PPPlot.setWindowTitle(_translate("PPPlot", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PPPlot = QtWidgets.QWidget()
    ui = Ui_PPPlot()
    ui.setupUi(PPPlot)
    PPPlot.show()
    sys.exit(app.exec_())
