# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/plot_properties.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PProps(object):
    def setupUi(self, PProps):
        PProps.setObjectName("PProps")
        PProps.resize(690, 662)
        self.gridLayout_2 = QtWidgets.QGridLayout(PProps)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_4 = QtWidgets.QWidget(PProps)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.cb_Plots = QtWidgets.QComboBox(self.widget_4)
        self.cb_Plots.setObjectName("cb_Plots")
        self.gridLayout_5.addWidget(self.cb_Plots, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.widget_4, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(PProps)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.dsb_Line_Width_2 = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.dsb_Line_Width_2.setMinimum(0.5)
        self.dsb_Line_Width_2.setSingleStep(1.0)
        self.dsb_Line_Width_2.setProperty("value", 1.0)
        self.dsb_Line_Width_2.setObjectName("dsb_Line_Width_2")
        self.gridLayout_7.addWidget(self.dsb_Line_Width_2, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 0, 1, 1)
        self.cb_Line_Style = QtWidgets.QComboBox(self.widget_3)
        self.cb_Line_Style.setObjectName("cb_Line_Style")
        self.cb_Line_Style.addItem("")
        self.cb_Line_Style.addItem("")
        self.cb_Line_Style.addItem("")
        self.gridLayout_7.addWidget(self.cb_Line_Style, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 4, 0, 1, 1)
        self.cb_Marker = QtWidgets.QComboBox(self.widget_3)
        self.cb_Marker.setObjectName("cb_Marker")
        self.gridLayout_7.addWidget(self.cb_Marker, 1, 1, 1, 1)
        self.db_Marker_Size = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.db_Marker_Size.setObjectName("db_Marker_Size")
        self.gridLayout_7.addWidget(self.db_Marker_Size, 1, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 630, 458))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_9.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.Labels = QtWidgets.QWidget()
        self.Labels.setObjectName("Labels")
        self.gridLayout = QtWidgets.QGridLayout(self.Labels)
        self.gridLayout.setObjectName("gridLayout")
        self.w_Label_Size = QtWidgets.QWidget(self.Labels)
        self.w_Label_Size.setObjectName("w_Label_Size")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.w_Label_Size)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.sb_Legend_Tick = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_Legend_Tick.setSingleStep(1)
        self.sb_Legend_Tick.setProperty("value", 18)
        self.sb_Legend_Tick.setObjectName("sb_Legend_Tick")
        self.gridLayout_13.addWidget(self.sb_Legend_Tick, 4, 5, 1, 1)
        self.sb_Legend = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_Legend.setSingleStep(1)
        self.sb_Legend.setProperty("value", 18)
        self.sb_Legend.setObjectName("sb_Legend")
        self.gridLayout_13.addWidget(self.sb_Legend, 4, 3, 1, 1)
        self.sb_Marker = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_Marker.setSingleStep(1)
        self.sb_Marker.setProperty("value", 18)
        self.sb_Marker.setObjectName("sb_Marker")
        self.gridLayout_13.addWidget(self.sb_Marker, 5, 5, 1, 1)
        self.sb_Title = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_Title.setSingleStep(1)
        self.sb_Title.setProperty("value", 18)
        self.sb_Title.setObjectName("sb_Title")
        self.gridLayout_13.addWidget(self.sb_Title, 5, 3, 1, 1)
        self.sb_YLabel = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_YLabel.setSingleStep(1)
        self.sb_YLabel.setProperty("value", 18)
        self.sb_YLabel.setObjectName("sb_YLabel")
        self.gridLayout_13.addWidget(self.sb_YLabel, 3, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_43.setObjectName("label_43")
        self.gridLayout_13.addWidget(self.label_43, 5, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 5, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_38.setObjectName("label_38")
        self.gridLayout_13.addWidget(self.label_38, 2, 4, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_42.setObjectName("label_42")
        self.gridLayout_13.addWidget(self.label_42, 4, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_40.setObjectName("label_40")
        self.gridLayout_13.addWidget(self.label_40, 3, 4, 1, 1)
        self.sb_YTick = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_YTick.setSingleStep(1)
        self.sb_YTick.setProperty("value", 18)
        self.sb_YTick.setObjectName("sb_YTick")
        self.gridLayout_13.addWidget(self.sb_YTick, 3, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_41.setObjectName("label_41")
        self.gridLayout_13.addWidget(self.label_41, 4, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_37.setObjectName("label_37")
        self.gridLayout_13.addWidget(self.label_37, 2, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_39.setObjectName("label_39")
        self.gridLayout_13.addWidget(self.label_39, 3, 2, 1, 1)
        self.sb_XTick = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_XTick.setSingleStep(1)
        self.sb_XTick.setProperty("value", 18)
        self.sb_XTick.setObjectName("sb_XTick")
        self.gridLayout_13.addWidget(self.sb_XTick, 2, 5, 1, 1)
        self.sb_XLabel = QtWidgets.QSpinBox(self.w_Label_Size)
        self.sb_XLabel.setSingleStep(1)
        self.sb_XLabel.setProperty("value", 18)
        self.sb_XLabel.setObjectName("sb_XLabel")
        self.gridLayout_13.addWidget(self.sb_XLabel, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.w_Label_Size)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_2.setObjectName("label_2")
        self.gridLayout_13.addWidget(self.label_2, 3, 0, 1, 1)
        self.le_XLabel = QtWidgets.QLineEdit(self.w_Label_Size)
        self.le_XLabel.setObjectName("le_XLabel")
        self.gridLayout_13.addWidget(self.le_XLabel, 2, 1, 1, 1)
        self.le_YLabel = QtWidgets.QLineEdit(self.w_Label_Size)
        self.le_YLabel.setObjectName("le_YLabel")
        self.gridLayout_13.addWidget(self.le_YLabel, 3, 1, 1, 1)
        self.le_Title = QtWidgets.QLineEdit(self.w_Label_Size)
        self.le_Title.setObjectName("le_Title")
        self.gridLayout_13.addWidget(self.le_Title, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_3.setObjectName("label_3")
        self.gridLayout_13.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.w_Label_Size)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 4, 0, 1, 1)
        self.le_Legend = QtWidgets.QLineEdit(self.w_Label_Size)
        self.le_Legend.setObjectName("le_Legend")
        self.gridLayout_13.addWidget(self.le_Legend, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.w_Label_Size, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Labels, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_29 = QtWidgets.QLabel(self.tab_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_12.addWidget(self.label_29, 2, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_7, 1, 1, 1, 1)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.gridLayout_12.addWidget(self.doubleSpinBox_12, 1, 3, 1, 1)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_13.setMinimum(0.1)
        self.doubleSpinBox_13.setProperty("value", 0.8)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.gridLayout_12.addWidget(self.doubleSpinBox_13, 2, 3, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_8, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.tab_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 1, 2, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_6, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.tab_3)
        self.label_30.setObjectName("label_30")
        self.gridLayout_12.addWidget(self.label_30, 3, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_12.addWidget(self.label_31, 0, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_5, 3, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.tab_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_12.addWidget(self.label_34, 2, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.tab_3)
        self.label_36.setObjectName("label_36")
        self.gridLayout_12.addWidget(self.label_36, 0, 2, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_10, 0, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 3, 2, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_9, 3, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem3, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 604, 928))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_14.addWidget(self.pushButton, 0, 0, 1, 2)
        self.w_Spines = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Spines.setObjectName("w_Spines")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.w_Spines)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox_4 = QtWidgets.QCheckBox(self.w_Spines)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_10.addWidget(self.checkBox_4, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.w_Spines)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_10.addWidget(self.checkBox, 0, 1, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.w_Spines)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_10.addWidget(self.checkBox_2, 1, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.w_Spines)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_10.addWidget(self.checkBox_3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem4, 2, 1, 1, 1)
        self.gridLayout_14.addWidget(self.w_Spines, 9, 0, 1, 2)
        self.pb_Spines = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Spines.setCheckable(True)
        self.pb_Spines.setObjectName("pb_Spines")
        self.gridLayout_14.addWidget(self.pb_Spines, 8, 0, 1, 2)
        self.pb_Axis = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Axis.setCheckable(True)
        self.pb_Axis.setObjectName("pb_Axis")
        self.gridLayout_14.addWidget(self.pb_Axis, 6, 0, 1, 2)
        self.w_Axis = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Axis.setObjectName("w_Axis")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.w_Axis)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.dsb_Label_Size = QtWidgets.QDoubleSpinBox(self.w_Axis)
        self.dsb_Label_Size.setMinimum(0.5)
        self.dsb_Label_Size.setObjectName("dsb_Label_Size")
        self.gridLayout_15.addWidget(self.dsb_Label_Size, 3, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.w_Axis)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.w_Axis)
        self.label_21.setObjectName("label_21")
        self.gridLayout_15.addWidget(self.label_21, 3, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.w_Axis)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.w_Axis)
        self.label_17.setObjectName("label_17")
        self.gridLayout_15.addWidget(self.label_17, 1, 0, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.w_Axis)
        self.comboBox_11.setObjectName("comboBox_11")
        self.gridLayout_15.addWidget(self.comboBox_11, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.w_Axis)
        self.label_16.setObjectName("label_16")
        self.gridLayout_15.addWidget(self.label_16, 0, 2, 1, 1)
        self.dsb_Line_Width = QtWidgets.QDoubleSpinBox(self.w_Axis)
        self.dsb_Line_Width.setMinimum(0.5)
        self.dsb_Line_Width.setProperty("value", 1.0)
        self.dsb_Line_Width.setObjectName("dsb_Line_Width")
        self.gridLayout_15.addWidget(self.dsb_Line_Width, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.w_Axis)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 1, 2, 1, 1)
        self.comboBox_12 = QtWidgets.QComboBox(self.w_Axis)
        self.comboBox_12.setObjectName("comboBox_12")
        self.gridLayout_15.addWidget(self.comboBox_12, 0, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.w_Axis)
        self.label_15.setObjectName("label_15")
        self.gridLayout_15.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.w_Axis)
        self.label_19.setObjectName("label_19")
        self.gridLayout_15.addWidget(self.label_19, 2, 0, 1, 1)
        self.dsb_Label_Pad = QtWidgets.QDoubleSpinBox(self.w_Axis)
        self.dsb_Label_Pad.setObjectName("dsb_Label_Pad")
        self.gridLayout_15.addWidget(self.dsb_Label_Pad, 3, 3, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.w_Axis)
        self.label_22.setObjectName("label_22")
        self.gridLayout_15.addWidget(self.label_22, 4, 0, 1, 1)
        self.dsb_Label_Weight = QtWidgets.QDoubleSpinBox(self.w_Axis)
        self.dsb_Label_Weight.setMinimum(0.5)
        self.dsb_Label_Weight.setObjectName("dsb_Label_Weight")
        self.gridLayout_15.addWidget(self.dsb_Label_Weight, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.w_Axis)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 4, 2, 1, 1)
        self.comboBox_13 = QtWidgets.QComboBox(self.w_Axis)
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_15.addWidget(self.comboBox_13, 4, 3, 1, 1)
        self.gridLayout_14.addWidget(self.w_Axis, 7, 0, 1, 2)
        self.pb_Margin = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pb_Margin.setCheckable(True)
        self.pb_Margin.setObjectName("pb_Margin")
        self.gridLayout_14.addWidget(self.pb_Margin, 4, 0, 1, 2)
        self.w_Margin = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.w_Margin.setObjectName("w_Margin")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.w_Margin)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_27 = QtWidgets.QLabel(self.w_Margin)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.w_Margin)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.w_Margin)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 0, 0, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.w_Margin)
        self.doubleSpinBox_9.setMinimum(0.5)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_11.addWidget(self.doubleSpinBox_9, 0, 1, 1, 1)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.w_Margin)
        self.doubleSpinBox_10.setMinimum(0.5)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.gridLayout_11.addWidget(self.doubleSpinBox_10, 1, 1, 1, 1)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.w_Margin)
        self.doubleSpinBox_11.setMinimum(0.5)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.gridLayout_11.addWidget(self.doubleSpinBox_11, 3, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem5, 4, 0, 1, 1)
        self.gridLayout_14.addWidget(self.w_Margin, 5, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem6, 10, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.cb_X_Scale = QtWidgets.QComboBox(self.widget_7)
        self.cb_X_Scale.setObjectName("cb_X_Scale")
        self.cb_X_Scale.addItem("")
        self.cb_X_Scale.addItem("")
        self.gridLayout_18.addWidget(self.cb_X_Scale, 1, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget_7)
        self.label_50.setObjectName("label_50")
        self.gridLayout_18.addWidget(self.label_50, 1, 0, 1, 1)
        self.cb_Y_Scale = QtWidgets.QComboBox(self.widget_7)
        self.cb_Y_Scale.setObjectName("cb_Y_Scale")
        self.cb_Y_Scale.addItem("")
        self.cb_Y_Scale.addItem("")
        self.gridLayout_18.addWidget(self.cb_Y_Scale, 1, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_7)
        self.label_51.setObjectName("label_51")
        self.gridLayout_18.addWidget(self.label_51, 1, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.widget_7)
        self.label_49.setObjectName("label_49")
        self.gridLayout_18.addWidget(self.label_49, 0, 0, 1, 4)
        self.gridLayout_8.addWidget(self.widget_7, 5, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_47 = QtWidgets.QLabel(self.widget_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_16.addWidget(self.label_47, 2, 2, 1, 1)
        self.dsb_XPos = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.dsb_XPos.setMinimum(0.1)
        self.dsb_XPos.setMaximum(1.0)
        self.dsb_XPos.setSingleStep(0.01)
        self.dsb_XPos.setProperty("value", 0.65)
        self.dsb_XPos.setObjectName("dsb_XPos")
        self.gridLayout_16.addWidget(self.dsb_XPos, 2, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.widget_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_16.addWidget(self.label_46, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.widget_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_16.addWidget(self.label_45, 0, 0, 1, 4)
        self.dsb_YPos = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.dsb_YPos.setMinimum(0.1)
        self.dsb_YPos.setMaximum(1.0)
        self.dsb_YPos.setSingleStep(0.01)
        self.dsb_YPos.setProperty("value", 0.57)
        self.dsb_YPos.setObjectName("dsb_YPos")
        self.gridLayout_16.addWidget(self.dsb_YPos, 2, 3, 1, 1)
        self.dsb_XWidth = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.dsb_XWidth.setMinimum(0.1)
        self.dsb_XWidth.setMaximum(1.0)
        self.dsb_XWidth.setSingleStep(0.01)
        self.dsb_XWidth.setProperty("value", 0.34)
        self.dsb_XWidth.setObjectName("dsb_XWidth")
        self.gridLayout_16.addWidget(self.dsb_XWidth, 3, 1, 1, 1)
        self.dsb_YWidth = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.dsb_YWidth.setMinimum(0.1)
        self.dsb_YWidth.setMaximum(1.0)
        self.dsb_YWidth.setSingleStep(0.01)
        self.dsb_YWidth.setProperty("value", 0.4)
        self.dsb_YWidth.setObjectName("dsb_YWidth")
        self.gridLayout_16.addWidget(self.dsb_YWidth, 3, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.widget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_16.addWidget(self.label_52, 3, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.widget_2)
        self.label_53.setObjectName("label_53")
        self.gridLayout_16.addWidget(self.label_53, 3, 2, 1, 1)
        self.gridLayout_8.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_17.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_17.addWidget(self.label_6, 1, 2, 1, 1)
        self.dsb_X1 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.dsb_X1.setObjectName("dsb_X1")
        self.gridLayout_17.addWidget(self.dsb_X1, 1, 3, 1, 1)
        self.dsb_X0 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.dsb_X0.setObjectName("dsb_X0")
        self.gridLayout_17.addWidget(self.dsb_X0, 1, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.widget_6)
        self.label_48.setObjectName("label_48")
        self.gridLayout_17.addWidget(self.label_48, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_17.addWidget(self.label_25, 2, 0, 1, 1)
        self.dsb_Y0 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.dsb_Y0.setObjectName("dsb_Y0")
        self.gridLayout_17.addWidget(self.dsb_Y0, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_17.addWidget(self.label_44, 2, 2, 1, 1)
        self.dsb_Y1 = QtWidgets.QDoubleSpinBox(self.widget_6)
        self.dsb_Y1.setObjectName("dsb_Y1")
        self.gridLayout_17.addWidget(self.dsb_Y1, 2, 3, 1, 1)
        self.gridLayout_8.addWidget(self.widget_6, 2, 0, 1, 1)
        self.cb_Show_Hide_Inset = QtWidgets.QCheckBox(self.widget)
        self.cb_Show_Hide_Inset.setText("")
        self.cb_Show_Hide_Inset.setObjectName("cb_Show_Hide_Inset")
        self.gridLayout_8.addWidget(self.cb_Show_Hide_Inset, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.widget, 1, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(PProps)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pb_Save_rcParams = QtWidgets.QPushButton(self.widget_5)
        self.pb_Save_rcParams.setObjectName("pb_Save_rcParams")
        self.gridLayout_6.addWidget(self.pb_Save_rcParams, 0, 1, 1, 1)
        self.pb_Load_rcParams = QtWidgets.QPushButton(self.widget_5)
        self.pb_Load_rcParams.setObjectName("pb_Load_rcParams")
        self.gridLayout_6.addWidget(self.pb_Load_rcParams, 0, 0, 1, 1)
        self.pb_Apply = QtWidgets.QPushButton(self.widget_5)
        self.pb_Apply.setObjectName("pb_Apply")
        self.gridLayout_6.addWidget(self.pb_Apply, 0, 2, 1, 1)
        self.pb_Cancel = QtWidgets.QPushButton(self.widget_5)
        self.pb_Cancel.setObjectName("pb_Cancel")
        self.gridLayout_6.addWidget(self.pb_Cancel, 0, 4, 1, 1)
        self.pb_Ok = QtWidgets.QPushButton(self.widget_5)
        self.pb_Ok.setObjectName("pb_Ok")
        self.gridLayout_6.addWidget(self.pb_Ok, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget_5, 2, 0, 1, 1)

        self.retranslateUi(PProps)
        self.tabWidget.setCurrentIndex(4)
        self.pb_Margin.toggled['bool'].connect(self.w_Margin.setVisible)
        self.pb_Axis.toggled['bool'].connect(self.w_Axis.setVisible)
        self.pb_Spines.toggled['bool'].connect(self.w_Spines.setVisible)
        QtCore.QMetaObject.connectSlotsByName(PProps)

    def retranslateUi(self, PProps):
        _translate = QtCore.QCoreApplication.translate
        PProps.setWindowTitle(_translate("PProps", "Form"))
        self.label_7.setText(_translate("PProps", "Plot"))
        self.label_12.setText(_translate("PProps", "TextLabel"))
        self.label_11.setText(_translate("PProps", "TextLabel"))
        self.label_9.setText(_translate("PProps", "Line style"))
        self.label_8.setText(_translate("PProps", "Line width"))
        self.cb_Line_Style.setItemText(0, _translate("PProps", "-"))
        self.cb_Line_Style.setItemText(1, _translate("PProps", "--"))
        self.cb_Line_Style.setItemText(2, _translate("PProps", "-.-."))
        self.label_10.setText(_translate("PProps", "Marker"))
        self.label_13.setText(_translate("PProps", "TextLabel"))
        self.label_14.setText(_translate("PProps", "Marker size"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("PProps", "Lines"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("PProps", "Scatter"))
        self.label_43.setText(_translate("PProps", "Title"))
        self.label_24.setText(_translate("PProps", "Marker"))
        self.label_38.setText(_translate("PProps", "xtick"))
        self.label_42.setText(_translate("PProps", "Legend tick"))
        self.label_40.setText(_translate("PProps", "ytick"))
        self.label_41.setText(_translate("PProps", "Legend"))
        self.label_37.setText(_translate("PProps", "xlabel"))
        self.label_39.setText(_translate("PProps", "ylabel"))
        self.label.setText(_translate("PProps", "XLabel"))
        self.label_2.setText(_translate("PProps", "YLabel"))
        self.le_XLabel.setText(_translate("PProps", "$F_1$"))
        self.le_YLabel.setText(_translate("PProps", "$F_2$"))
        self.label_3.setText(_translate("PProps", "Title"))
        self.label_4.setText(_translate("PProps", "Legend"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Labels), _translate("PProps", "Labels"))
        self.label_29.setText(_translate("PProps", "facecolor"))
        self.comboBox_7.setItemText(0, _translate("PProps", "True"))
        self.comboBox_7.setItemText(1, _translate("PProps", "False"))
        self.comboBox_8.setItemText(0, _translate("PProps", "inherit"))
        self.label_32.setText(_translate("PProps", "Frame on"))
        self.label_33.setText(_translate("PProps", "Frame alpha"))
        self.comboBox_6.setItemText(0, _translate("PProps", "best"))
        self.comboBox_6.setItemText(1, _translate("PProps", "top right"))
        self.comboBox_6.setItemText(2, _translate("PProps", "top left"))
        self.comboBox_6.setItemText(3, _translate("PProps", "bottom left"))
        self.comboBox_6.setItemText(4, _translate("PProps", "botom right"))
        self.label_30.setText(_translate("PProps", "fancybox"))
        self.label_31.setText(_translate("PProps", "Location"))
        self.comboBox_5.setItemText(0, _translate("PProps", "True"))
        self.comboBox_5.setItemText(1, _translate("PProps", "False"))
        self.label_34.setText(_translate("PProps", "edge color"))
        self.label_36.setText(_translate("PProps", "Font size"))
        self.comboBox_10.setItemText(0, _translate("PProps", "small"))
        self.comboBox_10.setItemText(1, _translate("PProps", "medium"))
        self.comboBox_10.setItemText(2, _translate("PProps", "large"))
        self.label_35.setText(_translate("PProps", "shadow"))
        self.comboBox_9.setItemText(0, _translate("PProps", "False"))
        self.comboBox_9.setItemText(1, _translate("PProps", "True"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("PProps", "Legend"))
        self.pushButton.setText(_translate("PProps", "Inset Axis"))
        self.checkBox_4.setText(_translate("PProps", "Top"))
        self.checkBox.setText(_translate("PProps", "Right"))
        self.checkBox_2.setText(_translate("PProps", "Bottom"))
        self.checkBox_3.setText(_translate("PProps", "Left"))
        self.pb_Spines.setText(_translate("PProps", "Spines"))
        self.pb_Axis.setText(_translate("PProps", "Axis"))
        self.comboBox_4.setItemText(0, _translate("PProps", "False"))
        self.comboBox_4.setItemText(1, _translate("PProps", "x axis"))
        self.comboBox_4.setItemText(2, _translate("PProps", "y axis"))
        self.comboBox_4.setItemText(3, _translate("PProps", "both"))
        self.label_21.setText(_translate("PProps", "Label pad"))
        self.label_20.setText(_translate("PProps", "Label size"))
        self.label_17.setText(_translate("PProps", "Line width"))
        self.label_16.setText(_translate("PProps", "Edge color"))
        self.label_18.setText(_translate("PProps", "TextLabel"))
        self.label_15.setText(_translate("PProps", "Face color"))
        self.label_19.setText(_translate("PProps", "Axis grid"))
        self.label_22.setText(_translate("PProps", "Label weight"))
        self.label_23.setText(_translate("PProps", "Label color"))
        self.pb_Margin.setText(_translate("PProps", "Margin"))
        self.label_27.setText(_translate("PProps", "y"))
        self.label_28.setText(_translate("PProps", "z"))
        self.label_26.setText(_translate("PProps", "x"))
        self.cb_X_Scale.setItemText(0, _translate("PProps", "linear"))
        self.cb_X_Scale.setItemText(1, _translate("PProps", "log"))
        self.label_50.setText(_translate("PProps", "x"))
        self.cb_Y_Scale.setItemText(0, _translate("PProps", "linear"))
        self.cb_Y_Scale.setItemText(1, _translate("PProps", "log"))
        self.label_51.setText(_translate("PProps", "y"))
        self.label_49.setText(_translate("PProps", "Scale"))
        self.label_47.setText(_translate("PProps", "y"))
        self.label_46.setText(_translate("PProps", "x"))
        self.label_45.setText(_translate("PProps", "Axis Position"))
        self.label_52.setText(_translate("PProps", "x width"))
        self.label_53.setText(_translate("PProps", "y width"))
        self.label_5.setText(_translate("PProps", "x0"))
        self.label_6.setText(_translate("PProps", "x1"))
        self.label_48.setText(_translate("PProps", "Bounds"))
        self.label_25.setText(_translate("PProps", "y0"))
        self.label_44.setText(_translate("PProps", "y1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("PProps", "Axis"))
        self.pb_Save_rcParams.setText(_translate("PProps", "Save"))
        self.pb_Load_rcParams.setText(_translate("PProps", "Load"))
        self.pb_Apply.setText(_translate("PProps", "Apply"))
        self.pb_Cancel.setText(_translate("PProps", "Cancel"))
        self.pb_Ok.setText(_translate("PProps", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PProps = QtWidgets.QWidget()
    ui = Ui_PProps()
    ui.setupUi(PProps)
    PProps.show()
    sys.exit(app.exec_())

